### ISSUE TITLE
Obscure errors when peer dependency warnings are not respected

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#100]
We had obscure errors in the browser:

`Failed to load resource: net::ERR_CONTENT_DECODING_FAILED`

This was caused by a very old version of the peer dependency `webpack-compression-plugin`.

We could have prevented this by checking for unmet peer dependency warnings when running yarn.

How can we make the use of **peer dependencies** less hazardous? 

I added a note to the Troubleshooting and Upgrade documents:

* https://github.com/shakacode/shakapacker/blob/master/docs/troubleshooting.md#incorrect-peer-dependencies
* https://github.com/shakacode/shakapacker/blob/master/docs/v6_upgrade.md#update-steps-to-v600-from-v600rc6

**Comment by tomdracz** [comment]
Might be worth adding a rake task to check peer dependencies and then hook it up to https://github.com/shakacode/shakapacker/blob/master/lib/tasks/webpacker/verify_install.rake#L3 so it runs together with other checks? @justin808
