### ISSUE TITLE
Default babel preset for shakapacker produces incorrect behavior by running in "loose" mode

### ISSUE THREAD

**Issue by MrLeebo** [shakacode/shakapacker#106]
Hi Shakapacker,

The default [babel preset](https://github.com/shakacode/shakapacker/blob/master/package/babel/preset.js#L28) includes a non-default option, "loose" mode, which changes the behavior of some javascript statements so that they defer from their native behaviors.

This can be really surprising, because the code in your bundle is doing something different from what you see when you run the same code in the Dev Console.

### Ruby version: 
```bash
ruby -v

ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin21]`
```
### Rails version: 
```bash
./bin/rails -v

Rails 6.0.4.7
```
### Webpacker version:
```bash
./bin/webpacker -v

webpack: 5.72.0
webpack-cli: 4.9.2
webpack-dev-server 4.8.1
```

### Expected behavior:

The code in the bundle should be consistent with the native behavior. For example, to get a unique array of values out of an array with duplicates, you can spread over a Set:

```js
const dups = [1, 1, 2, 2, 3, 3];
const uniq = [...new Set(dups)];

console.log(uniq) // [1, 2, 3]
```

The result is an array of unique values from the original input.

### Actual behavior:

In "loose" mode, the compiled output changes the logic slightly, and the raw source looks like this:

```js
[].concat(new Set(dups))
```

Which produces a different result:

```js
console.log(uniq) // [new Set([1, 2, 3])]
```

The array never iterates over the Set, the spread operation was ignored. Turning off "loose" mode makes it produce the correct result.

### Small, reproducible repo:

1. Go to this [Babel REPL](https://babeljs.io/repl#?browsers=%3E%201%25%2C%20last%205%20major%20versions%2C%20not%20dead&build=&builtIns=entry&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAJgVwA4RgXhgbQIwBoZ4wBM-JMAzPuQLoDcAUKJLAmAJYCO6WAdH2AFMA7jADKAqAApEKAJR16jcBBAAbAT1UgA5pNadZ9IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.17.9&externalPlugins=&assumptions=%7B%7D)
2. Open DevTools Console to observe the output
3. Toggle "Loose" on and off to see the change it produces in the compiled output and in the `console.log` output

Alternatively:

1. Follow the Installation steps in the README
4. Copy the code snippet above into `app/javascript/application.js` and run the app.

The culprit is this line in the preset: https://github.com/shakacode/shakapacker/blob/master/package/babel/preset.js#L28

### Workaround:

You can manually fix the babel config by removing the babel preset from `package.json` and creating a new babel.config.js to toggle "loose" mode off:

```js
// babel.config.js
module.exports = function (api) {
  // fetch the default babel config
  const defaultConfigFunc = require("shakapacker/package/babel/preset.js");
  const resultConfig = defaultConfigFunc(api);

  // "@babel/preset-env" is always the 1st preset
  const [[, options]] = resultConfig.presets;
  options.loose = false;

  // you can also make any other babel config changes that you need here
  return resultConfig;
};

```

**Comment by tomdracz** [comment]
Thanks for reporting, this is certainly unexpected!

I think it makes sense to drop the loose setting. Easy enough to add through custom config if someone wants it. Will open up a PR

**Comment by justin808** [comment]
@tomdracz @MrLeebo super. Let's ship this asap. Just tell me when you're ready and I'll release.

**Comment by MrLeebo** [comment]
Do you know why loose mode was originally enabled? Babel assumptions give you more specific control over "loose" logic, so if we knew why it was originally turned on, it might make sense to add an assumption to cover that use case.

**Comment by tomdracz** [comment]
Added here a while back https://github.com/rails/webpacker/pull/2623

Don't see much rationale apart from less lines of code generated 🤷 The examples given definitely didn't seem to cover the cases that break here with iterables.

It's a dangerous default either way, especially for something where we don't really control the code being generated. It might be a breaking change though and we should document and treat it as such

**Comment by robotfelix** [comment]
@tomdracz @MrLeebo have a pat on the back from me for fixing this one 👏 

After much head-scratching over a bug that only seemed to raise itself in cucumber tests when run in CI, this issue turned out to be the gremlin that was stopping me from migrating an application from webpacker to shakapacker! 🎉
