### ISSUE TITLE
Wrong CSS url with assets in subdirectories on Windows 

### ISSUE THREAD

**Issue by daniel-rikowski** [shakacode/shakapacker#114]
Ruby version: 3.1
Rails version: 7.0
Webpacker version: 6.2.1

Expected behavior: CSS urls must not contain backslashes as path delimiters when using assets from subdirectories.

Actual behavior: If for example a CSS font url is used on Windows, the final asset url contains a mixture of forward and backward slashes. Backslashes are escape characters in CSS, resulting in invalid CSS and subsequent 404 errors.

The bug was introduced with https://github.com/shakacode/shakapacker/commit/af48749bb03786ca43c132457cb7c8b39fdc8774

**Details and fix:**

In `package/rules/file.js` there is a Webpack hook defined to override the filename of the asset generator. 

When Webpack calls this, `pathData.filename` contains a normalized asset path with forward slashes, even on Windows.
(The code in the `filename` function correctly assumes this at the `replace` and `split` calls.)

```js
  filename: (pathData) => {              // pathData.filename contains forward slashes only, even on Windows
      const folders = dirname(pathData.filename)
        .replace(`${sourcePath}/`, '')   // Hardcoded forward slash, correct
        .split('/')                      // Hardcoded forward slash, correct
        .slice(1)

      const foldersWithStatic = join('static', ...folders)  // Inserts backslashes on Windows -> Invalid CSS name

      return `${foldersWithStatic}/[name]-[hash][ext][query]`  // Hardcoded forward slash, correct.
    }
```

Since this is called from a Webpack context with already normalized path delimiters I'd say it's reasonable to just forgo `path.join` and just use `Array.join`, i.e.

```js
const foldersWithStatic = ['static', ...folders].join('/')
```

If you like I can create a pull request for this.

**Comment by tomdracz** [comment]
Hey @daniel-rikowski Thanks for reporting, if you can open up a PR, it would be great!
