### ISSUE TITLE
append_javascript_pack_tag inserts (debugging?) text into the DOM

### ISSUE THREAD

**Issue by sschafercdd** [shakacode/shakapacker#119]
A bug is a crash or incorrect behavior. If you have a debugging or troubleshooting question, please open a discussion on [Discussions Tab](https://github.com/shakacode/shakapacker/discussions).

Ruby version: 2.7.6
Rails version: (6.1.6)
Webpacker version: 6.3.0-rc.1

Expected behavior:

In app/views/layouts/hello_world.html.erb, we have:
    <%= append_javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'hello-world-bundle' %>

This should simply load the packs

Actual behavior:

This seems to work, but also inserts ["application"] into the DOM, where it's visible on the top of the page.

Small, reproducible repo:
https://github.com/sschafercdd/react_on_rails_demo_ssr_hmr/tree/demobug

**Comment by tomdracz** [comment]
@sschafercdd as per readme, correct usage of helper is using `<% %>` rather than `‹%= %›`

In ERB former just executes the statement and the latter prints out the result.

**Comment by tomdracz** [comment]
Happy to accept a PR that just returns nil from the helper so it doesn't matter whether you use <%= or <%
