### ISSUE TITLE
Releases link in upgrade docs

### ISSUE THREAD

**Issue by tomdracz** [shakacode/shakapacker#12]
The releases link in the v6_upgrade.md (https://github.com/shakacode/shakapacker/blob/master/docs/v6_upgrade.md?plain=1#L36) links to https://github.com/rails/webpacker/releases

The release page in rails/webpacker repo itself is empty. Will the shakapacker use this so we can update the link or is there a better link to reference versions (tags? https://github.com/shakacode/shakapacker/tags)

**Comment by justin808** [comment]
@tomdracz does this fix the issue?

https://github.com/shakacode/shakapacker/commit/388e9acd6c05e591865e0f1d64563d94df7bc401
