### ISSUE TITLE
V7 Items

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#122]
## Breaking Changes Requiring a Major Version Bump
1. Change references from `webpacker` to `shakapacker` #157 
1. Change the configuration so that the configuration runs with a function invocation of a passed configuration object rather than using globals.

## Other Suggestions (not required for v7)
1. Change to use rspec for new tests rather than minitest
1. Support a dummy test app for better tests

**Comment by tomdracz** [comment]
Hey @jherdman Glad you are interested in helping out! Please have a look at issues with [help wanted](https://github.com/shakacode/shakapacker/labels/help%20wanted) tag - latest 3 there should be fairly small-ish to tackle!

**Comment by jherdman** [comment]
> Change references from webpacker to shakapacker

I'm tackling this today.

**Comment by jherdman** [comment]
OK, so `webpacker` ➡️ `shakapacker` is pretty impactful. Are there PRs in flight that ought to land first?

**Comment by tomdracz** [comment]
> OK, so `webpacker` ➡️ `shakapacker` is pretty impactful. Are there PRs in flight that ought to land first?

Nothing in flight so far, although I think we will need to cut 6-x branch some point soon and just work on back porting any fixes to that where relevant while we keep v7 dev to the master branch.

@justin808 How do you want to play this?

**Comment by justin808** [comment]
We can make master v7 once we have the first PR that's definitely v7 only.

@jherdman Thanks for the help!!!

**Comment by justin808** [comment]
@tomdracz I added back PR #131 to the list in the issue description.

**Comment by justin808** [comment]
I'm very interested in getting a v7 with the global renaming of webpacker to shakapacker one.

Too many docs are too confusing with the dual names.

**Comment by jherdman** [comment]
Justin: if you're interested you can take this off of my plate, I've been a derailed at work.

**Comment by justin808** [comment]
I agree to all of the above, and this should be a simple change.

We do need a dummy test app.

**Comment by ahangarha** [comment]
Then I created two separate issues for these two tasks and close this one:
- Pass configuration as a Hash, not a path
- Create a comprehensive dummy app for tests

I add both of them to [the v7 Milestone](https://github.com/shakacode/shakapacker/milestone/1).
This issue can get closed and any required discussions can be continue in its dedicated issue.
