### ISSUE TITLE
SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by erosinlove** [shakacode/shakapacker#127]
I added a new component file in my project at `app/javascript/components/xxx.js` after compiling the project with `rbenv exec bundle exec rake assets:clean assets:precompile` command I got the error as below

```
ERROR -- : SyntaxError: Invalid regular expression: /^(https?://)?((([a-zd]([a-zd-]*[a-zd])*).)+[a-z]{2,}|((d{1,3}.){3}d{1,3}))(:d+)?(/[-a-zd%_.~+]*)*(?[&a-zd%_.~+=-]*)?(#[-a-zd_]*)?$/: Invalid group
    at new RegExp (<anonymous>)
    at /home/myusername/myproject/node_modules/webpack/lib/javascript/JavascriptParser.js:412:24
    at Hook.eval [as call] (eval at create (/home/myusername/myproject/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at JavascriptParser.evaluateExpression (/home/myusername/myproject/node_modules/webpack/lib/javascript/JavascriptParser.js:3193:25)
    at JavascriptParser.getRenameIdentifier (/home/myusername/myproject/node_modules/webpack/lib/javascript/JavascriptParser.js:1398:23)
    at JavascriptParser.walkVariableDeclaration (/home/myusername/myproject/node_modules/webpack/lib/javascript/JavascriptParser.js:2090:31)
    at JavascriptParser.walkStatement (/home/myusername/myproject/node_modules/webpack/lib/javascript/JavascriptParser.js:1598:10)
    at JavascriptParser.walkStatements (/home/myusername/myproject/node_modules/webpack/lib/javascript/JavascriptParser.js:1459:9)
    at /home/myusername/myproject/node_modules/webpack/lib/javascript/JavascriptParser.js:1633:9
    at JavascriptParser.inBlockScope (/home/myusername/myproject/node_modules/webpack/lib/javascript/JavascriptParser.js:3091:3)
```
After checked and verified I found that the error is coming from `import Dante from "Dante2"` that containing in component file
```
import React from "react";
import ReactDOM from "react-dom";
import Dante from "Dante2";

....
```
Can anyone advise how can I fix this?

Ruby version: 3.1.2
Rails version: 7.0.3
Shakapacker version: 6.3

**Comment by erosinlove** [comment]
Hi @tomdracz sorry, how can I provide a minimal reproduction repo, just add you to my project or how can I do that?

**Comment by erosinlove** [comment]
This is the code, the error is coming from `Dante2`
```
import React from "react";
import ReactDOM from "react-dom";
import Dante from "Dante2";

import { DanteImagePopoverConfig } from "Dante2/package/es/components/popovers/image.js";
import { DanteAnchorPopoverConfig } from "Dante2/package/es/components/popovers/link.js";
import { DanteInlineTooltipConfig } from "Dante2/package/es/components/popovers/addButton.js"; 
import { DanteTooltipConfig } from "Dante2/package/es/components/popovers/toolTip.js"; 
import { ImageBlockConfig } from "Dante2/package/es/components/blocks/image.js";
import { EmbedBlockConfig } from "Dante2/package/es/components/blocks/embed.js";
import { VideoBlockConfig } from "Dante2/package/es/components/blocks/video.js";
import { PlaceholderBlockConfig } from "Dante2/package/es/components/blocks/placeholder.js";

export default class InlineEditor extends React.Component {
  tooltipsConfig = () => {
    return [
      DanteImagePopoverConfig(),
      DanteAnchorPopoverConfig(),
      DanteTooltipConfig(),
    ];
  };

  widgetsConfig = () => {
    return [
      ImageBlockConfig(),
      EmbedBlockConfig(),
      VideoBlockConfig(),
      PlaceholderBlockConfig(),
    ];
  };

  componentDidMount() {
    $('[data-behavior="editor-cancel"]').on("click", function (e) {
      e.preventDefault();
      $("#inline-editor").removeClass("active");
    });
  }

  handleClick = (e) => {
    $("#inline-editor").addClass("active");
  };

  initialContent = () => {
    return this.props.content ? JSON.parse(this.props.content) : null;
  };

  saveMethod = (context, editorContent) => {
    $("#editor-body").val(JSON.stringify(editorContent));
    $("#editor-plain").val(context.getTextFromEditor(editorContent));
  };

  render() {
    return (
      <div className="medium-editable post-body" onClick={this.handleClick}>
        <Dante
          body_placeholder={"typing..."}
          content={this.initialContent()}
          data_storage={{
            url: "/dummy",
            save_handler: this.saveMethod,
          }}
          tooltips={this.tooltipsConfig()}
          widgets={this.widgetsConfig()}
        />
      </div>
    );
  }
}
```

**Comment by tomdracz** [comment]
Hey @erosinlove I've found this comment from you before https://github.com/rails/webpacker/issues/3236#issuecomment-1059946934

Are you still running `require.context( "components", true, /^(https?:\/\/)?((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(:\d+)?(\/[-a-z\d%_.~+]*)*(?:[&a-z\d%_.~+=-]*)?(#[-a-z\d_]*)?$/ );` somewhere in your app? 

Original ticket was asking about requiring all files under components directory so not entirely sure why this regex would be needed.

Had a look at the Dante repo for `/^(https?://)?((([a-zd]([a-zd-]*[a-zd])*).)+[a-z]{2,}|((d{1,3}.){3}d{1,3}))(:d+)?(/[-a-zd%_.~+]*)*(?[&a-zd%_.~+=-]*)?(#[-a-zd_]*)?$/` regular expression and cannot find it there so I expect it comes from somewhere in your app. Can you have a look and let me know what you use it for?

You can add me to your project if you want and I can take a look also.

**Comment by erosinlove** [comment]
When I remove the component files that contain `import Dante from "Dante2";` I can compile without any error

**Comment by tomdracz** [comment]
Hey @erosinlove 

Looks like this is coming from Dante indeed at https://github.com/michelson/dante2/blob/master/src/editor/components/decorators/link.js#L10-L26

Specifically https://github.com/michelson/dante2/blob/master/src/editor/components/decorators/link.js#L17 somewhere. I think the line needs to start with `'(\\?` rather than `'(\?` - I'm not a Regexp expert but I think this causes ? to be treated as quantifier rather than literal character.

Either way, nothing to do with Shakapacker. The regex is incorrect and won't even work in the browser so this is something that needs to be addressed by Dante maintainers.

Hope that helps!
