### ISSUE TITLE
Run bundle install automatically after releasing a new. gem version

### ISSUE THREAD

**Issue by tomdracz** [shakacode/shakapacker#128]
As it stands, running release task https://github.com/shakacode/shakapacker/blob/master/rakelib/release.rake doesn't do anything to update local `Gemfile.lock` file with new version.

Missing `Gemfile.lock` update means that the tests fail (as we're running `bundle install` with deployment flag https://github.com/shakacode/shakapacker/runs/6512746968?check_suite_focus=true) and we need to run `bundle install` and commit result after each release to make sure everything works as expected.

We should modify or create a new rake task that commits the new version change and runs bundle install after gem is released to streamline this process.

cc @justin808

**Comment by justin808** [comment]
@tomdracz any chance that you can throw in a PR for this?
