### ISSUE TITLE
Bundler does not load webpacker.rb or the rest of the gem

### ISSUE THREAD

**Issue by t27duck** [shakacode/shakapacker#13]
A bug is a crash or incorrect behavior. If you have a debugging or troubleshooting question, please open a discussion on the [Rails forum, category webpacker](https://discuss.rubyonrails.org/c/webpacker/10)

Ruby version: 3.0.3
Rails version: 6.1.x
Webpacker version: shakapacker 6.0.0.rc.12

Expected behavior:

Having `gem "shakapacker", "6.0.0.rc.12"` in the Gemfile properly loads up the new gem

Actual behavior:

The gemspec file is called shakapacker.gemspec and expects a shakeapcker.rb file in `lib/` to load up. But the file in `lib/` is still `webpacker.rb` so nothing in the gem appears to be loaded up.

Small, reproducible repo:

On an existing Rails app on Rail's webpacker 6 rc6 gem, change the gem in the Gemfile to `gem "shakapacker", "6.0.0.rc.12"` and go through any minor changes to work with rc12. Running the app will result in `no method javascript_pack_tag` error because nothing actually is bootstrapped.

A workaround that appears to be fine locally is to change the entry in the Gemfile to 

```ruby
gem "shakapacker", "6.0.0.rc.12", require: "webpacker"
```

Which properly has bundler require the webpacker.rb file and the rest of the gem.

**Comment by t27duck** [comment]
Alternatively, a "quick fix" can be to put a `shakapacker.rb` file in `lib/` and have it simply `require "webpacker"`

**Comment by justin808** [comment]
Fixed in rc.13.
