### ISSUE TITLE
Can't execute Rails Code in js.erb files

### ISSUE THREAD

**Issue by Windh0wl** [shakacode/shakapacker#137]
I am trying to get js.erb files to work with shakapacker. But so far i had no luck. As far as i know there is no installer for erb (bundle exec webpacker:install:erb) anymore like in previous webpacker versions, so this should be supported out of the box, am i correct?
what could i be doing wrong here? 

Currently i have the stock webpack.config.js

```
// /app/views/concept_maps/edit.html.erb

<% append_javascript_pack_tag 'test' %> 
```
This is my output:
```
Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/windhowl/Dokumente/CoMapEd/app/javascript/packs/test.js.erb: Unexpected token (1:0)

> 1 | <%logger.debug "this is rails code"%>
    | ^
    at instantiate (/home/windhowl/Dokumente/CoMapEd/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/home/windhowl/Dokumente/CoMapEd/node_modules/@babel/parser/lib/index.js:358:12)
    at Parser.raise (/home/windhowl/Dokumente/CoMapEd/node_modules/@babel/parser/lib/index.js:3341:19)
    at Parser.unexpected (/home/windhowl/Dokumente/CoMapEd/node_modules/@babel/parser/lib/index.js:3379:16)
    at Parser.parseExprAtom (/home/windhowl/Dokumente/CoMapEd/node_modules/@babel/parser/lib/index.js:13083:24)
    at Parser.parseExprSubscripts (/home/windhowl/Dokumente/CoMapEd/node_modules/@babel/parser/lib/index.js:12650:23)
    at Parser.parseUpdate (/home/windhowl/Dokumente/CoMapEd/node_modules/@babel/parser/lib/index.js:12629:21)
    at Parser.parseMaybeUnary (/home/windhowl/Dokumente/CoMapEd/node_modules/@babel/parser/lib/index.js:12600:23)
    at Parser.parseMaybeUnaryOrPrivate (/home/windhowl/Dokumente/CoMapEd/node_modules/@babel/parser/lib/index.js:12394:61)
    at Parser.parseExprOps (/home/windhowl/Dokumente/CoMapEd/node_modules/@babel/parser/lib/index.js:12401:23)

```

Ruby version: 2.7
Rails version: 7.0.2
Shakapacker version: 6.3

**Comment by tomdracz** [comment]
Have you got https://www.npmjs.com/package/rails-erb-loader package installed? This is needed to process erb files but don't think it's included by default.

If the package is installed and you're still facing issues, please provide a reproduction repo so we can take a closer look

**Comment by justin808** [comment]
Labelling as question until we determine if really a bug.

**Comment by Windh0wl** [comment]
I have created a blank project and everything worked fine. I'm providing you the repo i'm currently working on directly: https://github.com/muehling/CoMapEd/tree/Update_rails

In app/views/concept_maps/edit.html.erb i want to load the test.js.erb

When you start the server  you should be able to get to the edit view by typing in 'abc' if you previously seeded the postgres db. 

I hope you can get that running. if not please tell me so. and sorry i couldn't provide a simpler repo but the problem seems to be somewhere in this repo. Maybe the problem is even that i upgraded from rails 5 to 7 and have some dead code left..

Thank you very much in advance!

**Comment by tomdracz** [comment]
Hey @Windh0wl 

I think I've got this working. Looks like spring gem is causing the issue here https://github.com/usabilityhub/rails-erb-loader/issues/63

To try and get this working do the following:
- Run `bundle exec rails webpacker:clobber` to remove all compiled assets
- Run `bin/spring binstub --remove --all`
- `bundle remove spring && bundle install`

After this, start the server again and it should be now working. Not sure what's the actual cause behind the scenes but I recommend reading through the issue linked above for some insights.

**Comment by tomdracz** [comment]
@justin808 Separately might need to implement https://github.com/usabilityhub/rails-erb-loader#spring (i.e. adding `DISABLE_SPRING` env to the loader config to guard against this in the future

**Comment by Windh0wl** [comment]
Nice. I get it to work now with a two liner .js.erb but not yet with my /app/views/concept_maps/edit.html.erb .. 
I get the same error still. 

Is there some js syntax i may not use with .erb ?

**Comment by tomdracz** [comment]
@Windh0wl Hard to say, have you got comments in the file? Those are one of the things that might cause issues here

Ruby comments are prefixed with the hash, whereas JS ones are `//` which I think trips up the parser.

Essentially, what the `rails-erb-loader` is doing is following (from https://github.com/usabilityhub/rails-erb-loader/issues/63#issuecomment-707940303)

```
cat myfile | bin/rails runner <path to erb_transformer.rb> > output.js
```

- `myfile` is the input file to process (`test.js.erb` or similar)
- `path to erb_transformer.rb` - it's the path to the file in node modules directory for the package (i.e.`./node_modules/rails-erb-loader/erb_transformer.rb`)

You should be able to test your file with something like:
```
cat app/javascript/packs/test.js.erb  | bin/rails runner ./node_modules/rails-erb-loader/erb_transformer.rb __RAILS_ERB_LOADER_DELIMETER__ erb
```

The command above will succeed if your `.js.erb` file is valid and hopefully fail with something pointing you to the error if it's invalid

**Comment by Windh0wl** [comment]
awesome. that helped a ton. i can run simple ruby code now. would you happen to know how i can run `<%= t('.action_new_node')%>` to insert locales ? i already included `/* rails-erb-loader-dependencies ../config/locales/ */` in my .js.erb file but i keep getting the error `<main>': undefined method 't' for main:Object (NoMethodError)` when i run your suggested commands

**Comment by tomdracz** [comment]
I think that's because scoping the key by partial is the Railsy helper thing rather than `I18n.t` one:

https://github.com/rails/rails/blob/main/actionview/lib/action_view/helpers/translation_helper.rb#L128-L140

You should be able to use just `t()` in your normal views just fine. It's only the `js.erb` files that might need `I18n.t` and full translation path in order to work if you are trying to load translation there. Hope that helps!
