### ISSUE TITLE
New Rails 7 project errors with undefined method `deep_symbolize_keys' 

### ISSUE THREAD

**Issue by pickhardt** [shakacode/shakapacker#150]
I am trying to set up a new Rails 7 app to compile JSX for React. Unfortunately Rails 7 totally changed how things work, so I found this project which looks like it could help. However, I followed the instructions on the readme, but get this

Ruby version: 3.1.0
Rails version: 7.0.1
Webpacker version: shakapacker 6.4

Expected behavior: rails s starts up

Actual behavior: errors
"/Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shakapacker-6.4.0/lib/webpacker/configuration.rb:110:in `load': undefined method `deep_symbolize_keys' for nil:NilClass (NoMethodError)"

Small, reproducible repo: Make a new rails 7 app, install this project, and it gives this error.

**Comment by justin808** [comment]
@tomdracz @mage1711 @alexeyr Any ideas?

**Comment by alexeyr-ci1** [comment]
I'll try to reproduce and fix this tomorrow. Though 
1. why shakapacker 6.4.0 and not 6.4.1?
2. did you add any other gems?

**Comment by pickhardt** [comment]
Never mind, it seems like the installation didn't work. I tried again today and figured it out.

I'm still having other problems but at least there's no undefined method deep_symbolize_keys exception now.
