### ISSUE TITLE
Rename all references of webpacker to shakapacker

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#157]
This is the first item for v7.

- [x] Can we alias the constant Webpacker to Shakapacker? Should we display deprecation warnings?
- [x] Changelog
- [x] Tests and CI configuration
- [x] JS Code
- [x] Ruby Code
- [ ] Examples
- [x] Docs
- [x] Error messages
- [ ] Comments
- [ ] Update key example projects
- [ ] Effect of libraries
  - [ ] [React on Rails](https://github.com/shakacode/react_on_rails)
  - [ ] [React Rails](https://github.com/reactjs/react-rails)
- [ ] Generator effects for new app

**Comment by skyksandr** [comment]
@justin808, all, but `bin/webpacker` and `bin/webpacker-dev-server` or you would like it to be `bin/shakapacker` and `bin/shakapacker-dev-server`?

**Comment by justin808** [comment]
How can we do this to make the migration easiest?

**Comment by justin808** [comment]
![image](https://user-images.githubusercontent.com/1118459/197292689-4125dd31-6a60-4524-91b8-a14536b7109c.png)
![image](https://user-images.githubusercontent.com/1118459/197292851-7bdad809-35e9-4a49-b603-019f1c781c71.png)
![image](https://user-images.githubusercontent.com/1118459/197292867-8b610501-31cc-42fc-b939-73a607545788.png)

**Comment by alkesh26** [comment]
@justin808 Should we go with [this](https://stackoverflow.com/a/14149821) approach?

**Comment by justin808** [comment]
> @justin808 Should we go with [this](https://stackoverflow.com/a/14149821) approach?

@alkesh26 I don't think you understand the task for _this_ gem. We've already made the new gem here.

Maybe you can open an issue for https://github.com/rails/webpacker suggesting the deprecation notice on installs?

**Comment by vaukalak** [comment]
I think we might split this work into smaller chunks, of different complexity:

**logs / errors**

This is the simples one, since we just need to replace webpacker => shakapacker whenever we log anything.

**cli commands / files**

Here we need to add a replacement with `shakapacker` with fall-down to `webpacker` with a warning. However I believe that for some time those should be backward-compatible. Which means although the command will be `bin/shakapacker`, we still should support `bin/webpacker` (with a warning). Same for `webpacker.yml` file.

**code**

We need to rename all `*webpacker*` classes / functions to `*shakapacker*`, although we should create new `*webpacker*` classes / functions that would delegate to `*shakapacker*` and warn deprecation.

**Comment by vaukalak** [comment]
@ahangarha may I ask you to document here:
1 - generated files (like `webpacker.yml`) that need to be renamed.
2 - cli commands (like `bin/shakapacker `)
3 - public javascript / ruby code interfaces.

I think those 3 need a backward compatibility, so libraries / projects can be updated without pain.

**Comment by ahangarha** [comment]
We generally have the following:
- some executables in `./bin`
- some configurations in `./config`
- rake tasks
- the rest of the code is internal (as far as I have seen) and can be wrapped for compatibility for a while till we delete Webpacker.
- documentation

I think we can add a new rake task like `rake webpacker:upgrade_to_shacapacker` to ease these steps for the client.

We have a good set of tests (except for the generator) and I think we should modify the code in a way that our tests pass without any modification (so we ensure we have good backward compatibility)

**Comment by justin808** [comment]
I like the idea of an upgrade program, but I'm not sure if a rake task is the right place. What do other projects do?

**Comment by ahangarha** [comment]
> I'm not sure if a rake task is the right place. What do other projects do?
I got this idea from the Rails update task. It is not exactly this but I think we can utilize it in this way. This supposedly can help us to have a smooth migration till the moment we drop Webpacker entirely from the gem.

Today we will have a call to discuss this matter. Hopefully will explore other implementations.
