### ISSUE TITLE
The webpacker compilation lock is global

### ISSUE THREAD

**Issue by alexeyr-ci1** [shakacode/shakapacker#158]
https://github.com/shakacode/shakapacker/blob/b86a3508fd1f88444f5ca3f81c96a3e31d2ff823/lib/webpacker/compiler.rb#L22-L24
There is a potential problem here. Our lock file is global (created in `Dir.tmpdir` with a fixed name), so if we have 2 projects using Shakapacker compiling at the same time, then the second will wait for the first to finish and return true without actually compiling :( 

1. Should we use process id in the log file name? Or create it in the working directory?
2. If an input file changes while we are waiting, do we want to run Webpack again at the end?

_Originally posted by @alexeyr-ci1 in https://github.com/shakacode/shakapacker/pull/139#discussion_r913239041_

**Comment by artemave** [comment]
> Or create it in the working directory?

This. Or maybe base temp file name on current working directory.

> If an input file changes while we are waiting, do we want to run Webpack again at the end?

Good point. I reckon replacing `true` with `compile` on line 24 should do the trick.

**Comment by tomdracz** [comment]
+1 on temp file in the current directory

**Comment by flugsio** [comment]
Using a tempfile in the active or compilation target directory sounds like a good solution. I'm trying a workaround by setting the [TEMP env](https://github.com/ruby/ruby/blob/11871e49c4fe493d6b958046969bc863f7fb6627/lib/tmpdir.rb#L21-L22) during compilation

**Comment by justin808** [comment]
@ahangarha another good one for v7.
