### ISSUE TITLE
Ignore the Gemfile.lock in Shakapacker's root directory?

### ISSUE THREAD

**Issue by tomdracz** [shakacode/shakapacker#166]
### Discussed in https://github.com/shakacode/shakapacker/discussions/163

<div type='discussions-op-text'>

<sup>Originally posted by **RailsCod3rFuture** July  6, 2022</sup>
Given that the gem lock file is inside of the root directory for the gem -- its causing AWS to pickup anomalies & things that it consider vulnerabilities/outdated gems. Is it mandatory that we have the gemfile.lock stored with the gem?</div>

As per discussion above and https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/ we should not be checking Gemfile.lock into version control. While we're at it, it's also probably worth moving anything we've got in Gemfile to `.gemspec` to avoid duplication and clarify usage.

PRs welcome!

**Comment by justin808** [comment]
@tomdracz I agree.

We've done it that way forever for React on Rails.

**Comment by RailsCod3rFuture** [comment]
Working on the PR now.

**Comment by alexeyr-ci1** [comment]
Note that the current Bundler recommendation is the opposite https://bundler.io/guides/faq.html:

> Q: Should I commit my `Gemfile.lock` when writing a gem?
> 
> A: Yes, you should commit it. The presence of a `Gemfile.lock` in a gem's repository ensures that a fresh checkout of the repository uses the exact same set of dependencies every time. We believe this makes repositories more friendly towards new and existing contributors. Ideally, anyone should be able to clone the repo, run `bundle install`, and have passing tests. If you don't check in your `Gemfile.lock`, new contributors can get different versions of your dependencies, and run into failing tests that they don't know how to fix.
> 
> Q: But I have read that gems should not check in the Gemfile.lock!
> 
> A: The main advantage of not checking in your Gemfile.lock is that new checkouts (including CI) will immediately have failing tests if one of your dependencies changes in a breaking way. Instead of forcing every fresh checkout (and possible new contributor) to encounter broken builds, the Bundler team recommends either using a tool like [Dependabot](https://dependabot.com/) to automatically create a PR and run the test suite any time your dependencies release new versions. If you don't want to use a dependency monitoring bot, we suggest creating an additional daily CI build that deletes the Gemfile.lock before running `bundle install`. That way you, and others monitoring your CI status, will be the first to know about any failures from dependency changes.

> We've done it that way forever for React on Rails.

Coincidentally, I've mentioned this recommendation and my inconvenience from the lack of `Gemfile.lock` in an issue there: https://github.com/shakacode/react_on_rails/issues/1470

**Comment by tomdracz** [comment]
Is there a best of both worlds solution where e keep Gemfile.lock but not include it in the gem bundle?

https://github.com/shakacode/shakapacker/blob/master/webpacker.gemspec#L29 modifying files list in the gemspec maybe?

**Comment by RailsCod3rFuture** [comment]
Yes, @tomdracz -- I'm working on a PR for it now

**Comment by RailsCod3rFuture** [comment]
I tried that @tomdracz -- doesn't pass ci

**Comment by RailsCod3rFuture** [comment]
We'll have to settle for our current approach for now...Given that the rails version for the gem will show on vulnerability scanners even when the main repo is using patched versions

**Comment by jasonfb** [comment]
I think the issue is that you are including the entirity of the Gem's files into the bundled gem. you are doing so here in the gemspec:
https://github.com/shakacode/shakapacker/blob/master/webpacker.gemspec#L29

Typically I think this is a bad idea. For one thing, you are bundling all of the associated support files for the gem (the tests, etc) into everyone's Rails app, making all our apps more bloated. 

In my gems I use this pattern to filter out everything that is not a "core" file to the gem -- the Gem's tests, dummy app, extra stuff. Maybe try something like this:

https://github.com/jasonfb/hot-glue/blob/main/hot_glue.gemspec#L17

**Comment by Judahmeek** [comment]
Resolved by #169 & #174
