### ISSUE TITLE
Raise an error when javascript_pack_tag or stylesheet_pack_tag are called more than once

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#17]
See https://github.com/rails/webpacker/pull/3083 from @guillaumebriday.

Fixes https://github.com/rails/webpacker/issues/3068 

However, might not still be an issue per [this comment](https://github.com/rails/webpacker/issues/3068#issuecomment-905648010).

**Comment by justin808** [comment]
Hi @tomdracz, if you put together a PR with a reproduction case and tests, I'll give it a review ASAP.

Ideally, we can get this fixed in the next few days! and 🚢  :shipit:

**Comment by tomdracz** [comment]
@justin808 Added https://github.com/shakacode/shakapacker/pull/19 to raise on multiple calls

**Comment by Judahmeek** [comment]
Fixed by #19

**Comment by hishammalik** [comment]
This actually creates an issue whereby I have two separates packs of javascript. One is defered for optimization reason whereas the other cannot be deferred.

With this exception added, I'm unable to use both deferred: true and false option for two separate packs.

Should be reverted I think as there is no restriction in html as to how many script tags you can put.

**Comment by tomdracz** [comment]
@hishammalik Can you open a new issue so this doesn't get lost in the noise?
