### ISSUE TITLE
Mapping of `media/<some_dir>/<more_dirs>/image.png` to `static/<more_dirs>/image.png`

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#177]
@tomdracz per your comment here: https://github.com/shakacode/shakapacker/pull/47#issuecomment-1029014169

Why are you removing the top-level directory of `fonts` and `images` from the manifest and the output?

https://github.com/shakacode/shakapacker/pull/47/files#diff-716197750a05276089fff034fe03597e5d569526a8ea683fb0022cf69456cbc4R28

I'm doing an upgrade, and it seems odd to arbitrarily remove the top-level directory.

From one of the packs files:
```js
require.context("../images", true);
```

Then this line will have to change to `media/images`:
```ruby
asset_pack_url("media/images/some.png")
```

Why would we not change to:

```
asset_pack_url("static/images/some.png")
```

Per the old documentation:
https://github.com/rails/webpacker/blob/v5.4.3/docs/assets.md#link-in-your-rails-views

So I'm confused about why we're stripping the top-level folder regardless of the name.

We also need to update the upgrade documentation to reflect the rename from `media/<some_directory>` to `static`.

Should we remove the arbitrary stripping of the top-level directory? I think so.

**Comment by tomdracz** [comment]
Webpacker RC changed the output path to static but along the way stopped respecting nested folders. Fixed that but left dropping the parent folder to leave the behaviour the same for non nested files.

Not sure if webpacker before v6 ever left parent folder alone. I think it was putting files in different folders based on file type though

**Comment by justin808** [comment]
@tomdracz v5 left the parent folder alone.

So dropping the top-level folder results in changes shown above for v5 => v6 migrations.

**Comment by justin808** [comment]
@tomdracz for v7, are you in favor of removing the stripping of the top folder?

I see that you kept compatibility between the beta and the final version. I think we should have focused on v5 to v6 compatibility.

**Comment by jwoodrow** [comment]
I'm getting a strange behaviour where the manifest in `development` and `production` for example is build with `static/path_to_asset` but in the `test` environment it's build with the old way `media/path_to_asset` when using `shakapacker@6.5.1` and `rails@7.0.3.1`

I was also wondering why this changed from webpacker to shakapacker and came across this issue.

**Comment by tomdracz** [comment]
Yeah, happy to remove top folder stripping in next major release!

**Comment by justin808** [comment]
@jwoodrow see https://github.com/shakacode/shakapacker/issues/183.

**Comment by ahangarha** [comment]
@justin808 
Should we change the default behavior of Shakapacker or add an option to activate such a feature?

**Comment by justin808** [comment]
@ahangarha Probably!

**Comment by justin808** [comment]
@tomdracz we're close to a v7. Do you have time to make this change?
