### ISSUE TITLE
NODE_ENV needs to default to 'development' if not set

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#183]
# Problem

`NODE_ENV` == `test` needs to be saved for JS only code, such as running Jest and Storybook, and NEVER for rspec or other integration tests.

## Broken originally, like this:

https://github.com/rails/webpacker/blame/93386ed7e85928b38b46f3f3dd259ae3a9e59090/lib/install/bin/webpack

## Fixed:

https://github.com/rails/webpacker/pull/1359 

https://github.com/rails/webpacker/blame/33b6c05ddb615ffa1a860c274372e21876d71c01/lib/install/bin/webpack

```ruby
ENV["NODE_ENV"]  ||= "development"
```

But if one forgets to set NODE_ENV for production builds, the JS code is not optimized!

## This change broke the functionality:

https://github.com/shakacode/shakapacker/blame/master/lib/install/bin/webpacker#L9

```ruby
ENV["NODE_ENV"]  ||= ENV["RAILS_ENV"]
```

# The Suggested Fix

1. Reset the default back to NODE_ENV == development in the bin/webpacker and bin/webpacker-dev-server files
2. Need to ensure that `NODE_ENV` == `production`

```ruby
# don't overwrite, so use ||=
ENV['NODE_ENV'] ||= (ENV['RAILS_ENV'] == production) ? 'production' : 'development'
```

But since this code is only updated when one makes a new install, let's move the change here:

from the binstub
```ruby
Dir.chdir(APP_ROOT) do
  Webpacker::WebpackRunner.run(ARGV)
end
``` 

And update this file:

https://github.com/shakacode/shakapacker/blob/master/lib/webpacker/runner.rb

And then, the upgrade instructions suggest removing the setting of the NODE_ENV from the bin stubs.

**Comment by justin808** [comment]
@tomdracz @Judahmeek @alexeyr-ci1 please review.

**Comment by tomdracz** [comment]
Makes sense to me, looks like a sensible change!

**Comment by alexeyr-ci1** [comment]
> Makes sense to me, looks like a sensible change!

Agreed.

**Comment by alexeyr-ci1** [comment]
@justin808

**Comment by alexeyr-ci1** [comment]
@justin808 

> And then, the upgrade instructions suggest removing the setting of the NODE_ENV from the bin stubs.

Some people may be using the stubs directly. My suggestion would be to change them as well instead of removing.

**Comment by justin808** [comment]
> Some people may be using the stubs directly. My suggestion would be to change them as well instead of removing.

Yes, remove from the binstubs installed, and be sure to mention this in the CHANGELOG.
