### ISSUE TITLE
Help wanted for figuring ou webpack/webpacker/shakapacker and rails asset handling

### ISSUE THREAD

**Issue by alexvbush** [shakacode/shakapacker#184]
hi everyone, I'm not a full time rails dev and don't follow the community and the news about rails that closely. Was very sad to find out that webpacker was officially not supported by rails maintainers anymore but am very much relieved that Shakacode folks are supporting it with shakapacker! Thank you! 

That said, I am experiencing, seemingly never ending nightmarish, issues trying to upgrade my small production application from Rails 5 to Rails 7.  I've managed to resolve all the issues except the last one - migrating my asset management to shakapacker/webpack.

I am very sure that all the problems and hurdles I'm experiencing are due to tremendous gaps in my knowledge and understanding of the rails asset pipeline, webpacker, sprockets, configs, and everything in between. There is just so much "magic" with the setup rails has and the way webpacker/shakapacker wraps around webpack. (although again, I don't claim to know webpacker well at all to be certain that I would be using it correctly even in a plain "vanila" setup).
There is just so many competencies/skillsets/knowledge bases stacked on top of each other with all of this.....

**That said, I am sure I am not the only one and there are a lot of other "casual" devs or beginners who struggle the same way.**

I am writing this not to complain, or ask for free help (although I'd appreciate a hand), but to **propose a collaboration** of sort - I'd be happy to pair program with anyone knowledgable in these rails asset handling/webpack topics and record the **pairing sessions to post them on youtube for everyones benefit**. I run https://insideiosdev.com/ podcast and youtube channel https://www.youtube.com/c/InsideiOSDev I'd be happy to record all of it, edit, add shownotes, etc. and publish (perhaps on dedicated channel or on @shakacode's website and in readme for this repo?) to everyone who struggles just like me. I don't care for affiliation or anything like that, I just feel a lot of pain and think others do too.

What do you think @justin808 and everyone else? 

P.S. again, thank you for maintaining this gem. It's great to have a choice for more modular options on rails.

**Comment by justin808** [comment]
Hi @alexvbush, let's touch base next month, as I'm quite busy preparing for [Rails Remote Conference 2022](https://topenddevs.com/conferences/rails-remote-conf-2022#schedule).

If anybody is in a similar position and would like ShakaCode to take care of the migrations so that the team can focus on features, check out my article [ShakaCode Client Engagement Model](https://www.shakacode.com/blog/client-engagement-model/).

![image](https://user-images.githubusercontent.com/1118459/188127758-55a2c7d7-2f03-4393-aad9-7c7a2d8642d4.png)

**Comment by justin808** [comment]
@alexvbush I'm closing this as this is not an "issue." It belongs in discussions.
