### ISSUE TITLE
shakapacker yarn:install is combined with the rails yarn:install

### ISSUE THREAD

**Issue by bughit** [shakacode/shakapacker#188]
Ruby version: 2.6.9
Rails version: 5.2 - 7.0
Shakerpacker version: 6.5.1

[rails yarn:install](https://github.com/rails/rails/blob/5-2-stable/railties/lib/rails/tasks/yarn.rake)
[shakapacker yarn:install](https://github.com/shakacode/shakapacker/blob/master/lib/tasks/yarn.rake)

Both are loaded. Defining the task twice creates two consecutive actions. Executing yarn install twice may not be a big deal, but not ideal either. 

Expected behavior:

shakapacker yarn:install to be the only one

Actual behavior:

both shakapacker and rails yarn:install are executed

**Comment by Judahmeek** [comment]
It doesn't look like there's an easy solution for this.

While [Rake::Task.enhance adds tasks to a public array](https://github.com/ruby/rake/blob/1cb1d33266e3cc75112bc61d6ba2e981ca86c5ed/lib/rake/task.rb#L117) & each task in that array can be queried for its source location, more research would have to be done to determine when rails or shakapacker's assets:precompile enhancements are actually detectable.

As you can see below, when I checked the enhancements of `assets:precompile` through rails console in the development environment for [React on Rails's test application (which uses Shakapacker)](https://github.com/shakacode/react_on_rails/tree/master/spec/dummy), neither the rails nor the shakapacker enhancement show up:

```
Loading development environment (Rails 7.0.4)
[1] pry(main)> Rails.application.load_tasks 
=> #<Dummy::Application>
[2] pry(main)> x = Rake::Task["assets:precompile"]
=> <Rake::Task assets:precompile => [assets:compile_environment]>
[3] pry(main)> x.actions
=> [#<Proc:0x00007f9eff0329d8 /Users/judahmeek/.rvm/gems/ruby-2.7.5@pro/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:65>, #<Proc:0x00007f9f1422be78 /Users/judahmeek/.rvm/gems/ruby-2.7.5@pro/gems/react_on_rails-12.4.0/lib/tasks/assets.rake:29>]
[4] pry(main)> x.actions[0].source_location
=> ["/Users/judahmeek/.rvm/gems/ruby-2.7.5@pro/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb", 65]
[5] pry(main)> exit
```

**Comment by bughit** [comment]
I am removing it in the Rakefile

```rb
Rails.application.load_tasks

if Rake::Task.task_defined?('yarn:install')
  yarn_install_task = Rake::Task['yarn:install']
  rails_yarn_install_action = yarn_install_task.actions.find do |action_proc|
    file_name, = action_proc.source_location
    file_name&.end_with?('/lib/rails/tasks/yarn.rake')
  end
  yarn_install_task.actions.delete(rails_yarn_install_action) if rails_yarn_install_action
end
```
Whether a gem can hook into something after task load but before execution, to do the above, I haven't investigated.

**Comment by bughit** [comment]
can also be done in a prereq for 'yarn:install', which shakapacker can do

```rb
if Rake::Task.task_defined?('yarn:install')
  task '_clear_rails_yarn_install_action' do
    yarn_install_task = Rake::Task['yarn:install']
    rails_yarn_install_action = yarn_install_task.actions.find do |action_proc|
      file_name, = action_proc.source_location
      file_name&.end_with?('/lib/rails/tasks/yarn.rake')
    end
    yarn_install_task.actions.delete(rails_yarn_install_action) if rails_yarn_install_action
  end
  Rake::Task['yarn:install'].enhance ['_clear_rails_yarn_install_action']
end
```

**Comment by tomdracz** [comment]
We had this removed in https://github.com/shakacode/shakapacker/pull/131/files but brought it back with deprecation notice.

In general, I would keep this for V7 and remove once again, that whole enhancement malarkey is bit too magical for my tastes

**Comment by bughit** [comment]
the enhancement of assets:precompile is not the focus here

what matters is shakapacker and rails both define yarn:install so when it's invoked (whether by assets:precompile or manually) both actions will execute

**Comment by bughit** [comment]
@Judahmeek is the "help wanted" still needed? I already [provided](#issuecomment-1278182495) the solution/

**Comment by bughit** [comment]
@Judahmeek Which chnage closed this?

**Comment by bughit** [comment]
@ahangarha This was closed as completed after you assigned it to yourself. Did you push anything for this?

**Comment by Judahmeek** [comment]
@bughit I closed this issue because we're going to be removing the yarn install rake task in v7.

**Comment by bughit** [comment]
The deprecation is for automatic installation (i.e. precompile enhancement), why would you remove the yarn install task entirely?
