### ISSUE TITLE
Stuck on assets:precompile

### ISSUE THREAD

**Issue by MBM1607** [shakacode/shakapacker#189]
Ruby version: *2.7.4*
Rails version: 6.1.6
Webpacker version: 6.5.1

# Background
I have a repo with a lot of assets, some 200 js files and 100 scss files handled through shackapacker + webpack. 
In development & test environment it works gloriously and without a hitch.

Issue occurs in production, first when any asset changes then precompile doesn't re-compile it.

`rake webpacker:clobber` has to be run and only after that does it compile.

## Issue
In production on asset compilation, the command simply returns
`waiting for compilation to complete`
however, assets do not get compiled. I had to turn off the production server just to get the assets to compile correctly.

## Memory Issue?
It seems to me that the compilation process might be running out of memory. That would explain why stopping Nginx allows the compilation to complete. How can I optimize the process?

**Comment by Judahmeek** [comment]
Other than working with webpack devs to optimize their compilation process, the only optimization that I can think of would be some sort of code splitting, such as with React on Rails Pro & Loadable-Components or React v18's Suspense + React.lazy
