### ISSUE TITLE
Support for embed javascript files from gems / add to additional paths

### ISSUE THREAD

**Issue by danielnc** [shakacode/shakapacker#194]
I am moving to shakapacker from jsbundling(+webpacker) to simply a lot of the configurations and follow more of the rails conventions, but I have an issue where I was previously using Pagy in one of my stimulus controllers

To accomplish that previously this is what I had on my package.json

`"build": "PAGY_PATH=\"$(bundle show 'pagy')/lib/javascripts\" webpack --config ./config/webpack/webpack.config.js",`

And on my webpack.config.js I just used
```
  resolve: {
    modules: [
      process.env.PAGY_PATH,
    ],
  },
```

What can I do to also get the pagy gem install dir and use it on the additional_paths from webpack.yml?

**Comment by justin808** [comment]
Hi @danielnc, the use of the default webpack config object is optional! I'd recommend modifying the resulting webpack config object to meet your needs. Just import the default config, check it in the debugger, and modify the config object per your needs. Be sure to test for NODE_ENV equals development and production.
