### ISSUE TITLE
Please add support for pnpm

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#195]
Originally from @mattp0123

**Is your feature request related to a problem? Please describe.**

If one uses pnpm...

When I run `bin/rails generate react_on_rails:install`, it says:
```shell=
ERROR: yarn is required. Please install it before continuing. https://yarnpkg.com/en/docs/install
ERROR: react_on_rails generator prerequisites not met!
```

**Describe the solution you'd like**
Please add support for pnpm, it's a very powerful modern front-end tool.

**Comment by sharang-d** [comment]
Hey @Judahmeek, I see this was closed as completed but I can't find the relevant code or documentation. Can you point me to some?

**Comment by ahangarha** [comment]
@sharang-d I believe closing it as completed was a mistake. I changed the status to closed as not planned for now which is more appropriate. So we improve our focus on more important issues.

If you have an active use case for this, please let us know. We can open it up any time.

**Comment by sharang-d** [comment]
@ahangarha Got it, thanks.

We're moving to `pnpm` from `yarn` so I wanted to see if it works. We're redefining the rake tasks to use `pnpm` instead of `yarn` as it isn't supported but it'd be nice to have this gem support it directly.

**Comment by G-Rath** [comment]
If the idea is to try and support package managers in general (or at least "the big three"), it probably makes sense to update the title of this issue to reflect that, for visibility.

I personally support this, and would be very happy to help if folks are open to an iterative approach - I feel like the best path forward is probably to try and start with some "manual" conditional support, encapsulated into a class/module that could make sense to eventually publish into a dedicated gem for other libraries to use; from my personal experience dealing with supporting these packages managers, I've found the actual differences between them are easily handled in this sort of automation space.

<details>
<summary>Here's a straw man that I think could be a good approach to start with</summary>

```
class NotImplementedError < StandardError; end

class PackageManager
  # @param [PackageJson | nil] [package_json]
  def initialize(package_json = nil)
    # @type [PackageJson]
    @package_json = package_json
  end

  def install(opts = [])
    raise NotImplementedError
  end

  # @param [Array<String>] packages
  # @param [Symbol] type
  # @param [Array<String>] [opts]
  def add_and_install(packages, type = :production, opts = [])
    raise NotImplementedError
  end

  # @param [String] cmd
  # @param [Array<String>] args
  # @param [Array<String>] [opts]
  def run_script(cmd, args, opts = [])
    raise NotImplementedError
  end
end

class NpmPackageManager < PackageManager
  def install(opts = [])
    run(opts, "install", [])
  end

  def add_and_install(packages, type = :production, opts = [])
    if type == :peer
      add_peer_dependencies(packages)
      install(opts)

      return
    end

    run(opts, "install #{cmd}", [package_type_install_flag(type)] + packages)
  end

  def run_script(cmd, args, opts = [])
    run(opts, "run #{cmd} --", args)
  end

  private

  def run(opts, cmd, args)
    `npm #{opts.join(" ")} #{cmd} #{args.join(" ")}`
  end

  # @param [Array<String>] packages
  def add_peer_dependencies(packages)
    raise StandardError, "package.json is required for this" if @package_json.nil?

    @package_json.modify do |package_json|
      peer_dependencies = package_json.fetch("peerDependencies", {})

      packages.each do |pkg|
        scoped = pkg.start_with?("@")

        pkg = pkg.delete_prefix("@")
        pkg, version = pkg.split("@")

        version = "*" unless version
        pkg = "@#{pkg}" if scoped

        peer_dependencies[pkg] = version
      end

      package_json["peerDependencies"] = peer_dependencies
    end
  end

  def package_type_install_flag(type)
    case type
    when :production
      return "--save-prod"
    when :dev
      return "--save-dev"
    when :optional
      return "--save-optional"
    else
      raise StandardError, "unsupported package install type \"#{type}\""
    end
  end
end

class YarnPackageManager
  def install(opts = [])
    run(opts, "install", [])
  end

  def add_and_install(packages, type = :production, opts = [])
    run(opts, "add #{cmd}", [package_type_install_flag(type)] + packages)
  end

  def run_script(cmd, args, opts = [])
    run(opts, "run #{cmd}", args)
  end

  private

  def run(opts, cmd, args)
    `yarn #{opts.join(" ")} #{cmd} #{args.join(" ")}`
  end

  def package_type_install_flag(type)
    case type
    when :production
      return ""
    when :dev
      return "--dev"
    when :peer
      return "--peer"
    when :optional
      return "--optional"
    else
      raise StandardError, "unsupported package install type \"#{type}\""
    end
  end
end

class PnpmPackageManager
  def install(opts = [])
    run(opts, "install", [])
  end

  def add_and_install(packages, type = :production, opts = [])
    run(opts, "add #{cmd}", [package_type_install_flag(type)] + packages)
  end

  def run_script(cmd, args, opts = [])
    run(opts, "run #{cmd} --", args)
  end

  private

  def run(opts, cmd, args)
    `pnpm #{opts.join(" ")} #{cmd} #{args.join(" ")}`
  end

  def package_type_install_flag(type)
    case type
    when :production
      return "--save-prod"
    when :dev
      return "--save-dev"
    when :peer
      return "--save-peer"
    when :optional
      return "--save-optional"
    else
      raise StandardError, "unsupported package install type \"#{type}\""
    end
  end
end

class PackageJson
  # @return [PackageManager]
  attr_reader :manager

  def initialize(path_to_package_json, package_manager = nil)
    @path = path_to_package_json

    package_manager = determine_package_manager if package_manager.nil?

    use_package_manager(package_manager)
  end

  def use_package_manager(package_manager_name)
    case package_manager_name
    when :npm
      @manager = NpmPackageManager.new
    when :yarn
      @manager = YarnPackageManager.new
    when :pnpm
      @manager = PnpmPackageManager.new
    else
      raise StandardError, "unsupported package manager \"#{package_manager_name}\""
    end
  end

  def modify
    write_package_json(yield read_package_json)
  end

  private

  def read_package_json
    JSON.parse(File.read(@path))
  end

  def write_package_json(content)
    File.write(@path, JSON.pretty_generate(content))
  end

  def determine_package_manager
    read_package_json.fetch("packageManager", nil)&.to_sym
  end
end

package_json = PackageJson.new("package.json", :yarn)
package_json.manager.add_and_install(
  %w[
    eslint-plugin-react
    eslint-plugin-react-hooks
    eslint-plugin-jsx-a11y
    eslint-plugin-jest
    eslint-plugin-jest-formatting
    eslint-plugin-jest-dom
    eslint-plugin-testing-library
  ],
  :dev
)
```
</details>

**Comment by willemorvets** [comment]
I can take a shot at this... if that brings joy 🙂.

**Comment by ahangarha** [comment]
@willemorvets Why not? 🙂

**Comment by G-Rath** [comment]
I'm working on a thing for this - hoping to have something to show in the next couple of days

**Comment by G-Rath** [comment]
Ok I've marked my PR as ready for review, though it's got no documentation; it should still be usable and I'd love if people can try it out - to do so you want to set `SHAKAPACKER_USE_PACKAGE_JSON_GEM=true` in your env and then set `PACKAGE_JSON_FALLBACK_MANAGER` to either npm, yarn_classic, yarn_berry, or pnpm. Note that you'll have to handle ensuring the package manager is available.

I have also got a PR open for the Ackama [`rails-template`](https://github.com/ackama/rails-template/pull/466) which can be used to completely setup a new Rails project with Shakapacker and react-rails with any of the four package managers and with either the PnP or the node-modules linker if using Yarn Berry.

**Comment by G-Rath** [comment]
My PR has been landed and shipped as v7.2.0-rc.0 - if folks could try it out and report back how they find it, that would be great.

Should get released (still behind the feature flag) in v7.2.0 sometime in the next couple of weeks unless there are reports of major issues.

**Comment by dlackty** [comment]
As 7.2.0 has been released, I think this issue could be closed now?

**Comment by G-Rath** [comment]
No support is currently gated behind an env variable - we're going to do a new major soon that will remove that, at which point PNPM and NPM will be supported out of the box

**Comment by tomdracz** [comment]
Released with v8 RC so hoping it will land in full release soon!
