### ISSUE TITLE
Allow babel-loader 9.0

### ISSUE THREAD

**Issue by tagliala** [shakacode/shakapacker#196]
Babel loader released 9.0.0 a couple of days ago

Here it is the changelog: https://github.com/babel/babel-loader/releases/tag/v9.0.0

Ruby version: _not relevant_
Rails version: _not relevant_
shakapacker version: 6.5.4

### Desired behavior:
Allow the usage of babel-loader 9.x without warnings

### Actual behavior:
```
warning " > shakapacker@6.5.2" has incorrect peer dependency "babel-loader@^8.2.4".
```

**Comment by tomdracz** [comment]
Looking at changelog, we should be all good. Feel free to open PR @tagliala to allow 9.x.x of babel loader alongside ^8.2.4 version. If not picked up, I will try and open up PR myself in the next few days

**Comment by tagliala** [comment]
@tomdracz what about the dev dependency?

Should it bumped up to 9.0 for development?

**Comment by justin808** [comment]
Yes. Once we've confirmed it works!
