### ISSUE TITLE
[Windows] Errno::EACCES: Permission denied @ rb_file_s_symlink (config/webpacker.yml)

### ISSUE THREAD

**Issue by kevinbbd** [shakacode/shakapacker#203]
`Errno::EACCES: Permission denied @ rb_file_s_symlink - (../lib/install/config/webpacker.yml, C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shakapacker-6.5.2/config/webpacker.yml)`

An error occurred while installing shakapacker (6.5.2) on Ruby v2.7.6 installed on Windows 10 without elevated permissions, this error prevents Bundler from continuing. This stems from the symlink in the [config/webpacker.yml](https://github.com/shakacode/shakapacker/blob/master/config/webpacker.yml) - this could potentially be resolved by simply copying the contents of [lib/install/config/webpacker.yml](https://github.com/shakacode/shakapacker/blob/master/lib/install/config/webpacker.yml) to `config/webpacker.yml`. Avoiding the use of symlinks (rb_file_s_symlink) will allow the gem to be installed on Windows Ruby and work out of the box without requiring elevated/admin permissions.

Ruby version: 2.7.6
Rails version: 6.1.5
Shakapacker version: 6.5.2
Platform: Windows 10

Expected behavior: 
`bundle install` should work out of the box without requiring elevated permissions on Windows.

Actual behavior: 
`Errno::EACCES: Permission denied @ rb_file_s_symlink - (../lib/install/config/webpacker.yml, C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shakapacker-6.5.2/config/webpacker.yml)`

Reproducible steps:
- Install Ruby 2.7 on Windows 10
- Run `gem install shakapacker -v 6.5.2`
- Results is the error mentioned above (`Errno::EACCES: Permission denied @ rb_file_s_symlink`)

**Comment by justin808** [comment]
@kevinbbd can you try 6.5.4?

**Comment by justin808** [comment]
Can you see if older versions have this issue?

**Comment by kevinbbd** [comment]
Thanks for following up @justin808, greatly appreciated!

I tried installing v6.5.4 of the shakapacker gem and it resulted in the same error as the [symbolic link](https://github.com/shakacode/shakapacker/blob/v6.5.4/config/webpacker.yml) still exists in v6.5.4. 

rb_file_s_symlink error v6.5.4:
`Errno::EACCES: Permission denied @ rb_file_s_symlink - (../lib/install/config/webpacker.yml, C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shakapacker-6.5.4/config/webpacker.yml)`

Based on the git history it appears the symbolic link was introduced into shakapacker with [v6.0.0-rc7](https://github.com/shakacode/shakapacker/blob/v6.0.0-rc.7/config/webpacker.yml) and was also pre-existing in [rails/webpacker v6.0.0.rc.1](https://github.com/rails/webpacker/blob/v6.0.0.rc.1/config/webpacker.yml)

I also tried to install older versions of shakapacker (>=6.0.0-rc7) and rails/webpacker (>=6.0.0.rc.1) it yields the same error.

**Temporary solution**
In the meantime, the shakapacker dependency can be successfully installed if you download the gem using the git repo and tag directly. eg: `gem 'shakapacker', git: 'https://github.com/shakacode/shakapacker', tag: 'v6.5.4'`

**Comment by Judahmeek** [comment]
Should be resolved with 6.5.5 release
