### ISSUE TITLE
`net-protocol` already initialized constant log noise with Ruby 2.7.x

### ISSUE THREAD

**Issue by leastbad** [shakacode/shakapacker#206]
Ruby version: 2.7.4
Rails version: 7.0.4
Shakapacker version: 6.5

Expected behavior:

`rails c`, `rails s` or task running should operate as usual.

Actual behavior:

Shakapacker README suggests Ruby 2.6+ support, but when I run with any 2.7.x it spits out a bunch of log noise:

```
/home/leastbad/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError/home/leastbad/.rvm/gems/ruby-2.7.4/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/home/leastbad/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/leastbad/.rvm/gems/ruby-2.7.4/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/home/leastbad/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/leastbad/.rvm/gems/ruby-2.7.4/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was hereLoading development environment (Rails 7.0.4)
```

There are no warnings if you run it with Ruby 3.x.

Small, reproducible repo:

```bash
rails new myapp --skip-javascript
bundle add shakapacker --strict
rails webpacker:install
rails c
```

Switch between 2.7.4 and 3.1.2 to see the warnings or not.

**Comment by texpert** [comment]
Adding the following gems explicitly to the Gemfile helped me to get rid of this issue:

```
  gem 'net-http', require: false
  gem 'net-imap', require: false
  gem 'net-protocol', require: false
  gem 'net-smtp', require: false
```

**Comment by justin808** [comment]
What is the root issue? Seems to be that the gems are getting loaded twice, and maybe in different versions.

I'd like some feedback on the root cause before changing any code.

**Comment by texpert** [comment]
The issue is that the `net-xxx` modules have been separated into gems prior of their exclusion from `stdlib` in Ruby 3.0.

So, for Ruby version < 3.0 there are possible cases now, when the `stdlib` module is first loaded, but then the corresponding gem is required as well, causing this warnings to happen. See an example described here - https://github.com/ruby/net-imap/issues/16#issuecomment-803086765

Note: the issue couldn't be mitigated using the `gemspec` - only requiring the gems in the Gemfile helps.

**Comment by philayres** [comment]
For Rails 5, Ruby 2.7.6, this was more than noise, and caused issues with Selenium rspec tests. The net gems were installed when the mail gem was bumped from 2.7 to 2.8. I held it back to the previous version and this removed the explicit net gems from the Gemlock and "solved" my issues:

    gem 'mail', '2.7.1'

**Comment by Judahmeek** [comment]
Doesn't seem to be a shakapacker specific issue.
