### ISSUE TITLE
Allow webpack-cli 5.0

### ISSUE THREAD

**Issue by tagliala** [shakacode/shakapacker#209]
https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/CHANGELOG.md#500-2022-11-17

Ruby version: _not relevant_
Rails version: _not relevant_
shakapacker version: 6.5.4

### Desired behavior:
Allow the usage of webpack-cli 5.x without warnings

### Actual behavior:
```
warning " > shakapacker@6.5.4" has incorrect peer dependency "webpack-cli@^4.9.2".
```

**Comment by justin808** [comment]
@tagliala any chance that you can contribute a PR?

**Comment by tagliala** [comment]
@justin808 sure, I've also asked what do you prefer with https://github.com/shakacode/shakapacker/issues/196#issuecomment-1297012853
