### ISSUE TITLE
Working tree not clean when running `bundle exec rake`

### ISSUE THREAD

**Issue by tagliala** [shakacode/shakapacker#210]
Ruby version: 3.1
Rails version: n/a
Shakapacker version: master

### Expected behavior:
No changes to the working tree

### Actual behavior:
After running `bundle exec rake`, a new file is being created:

```
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	test/mounted_app/test/dummy/bin/yarn

nothing added to commit but untracked files present (use "git add" to track)
```

### Small, reproducible repo:

1. Clone this repo
2. Run `bundle exec rake`

---

Can't tell if the file should be committed or ignored, if you advise I can submit a PR

**Comment by ahangarha** [comment]
This is a known issue and will be addressed soon.
@justin808 I can fix this right now or fix it in the new RSpec tests.
I can address it either way.

**Comment by ahangarha** [comment]
This issue will be resolved with the tests
Thanks for pointing
