### ISSUE TITLE
Drop Node 12 support

### ISSUE THREAD

**Issue by tagliala** [shakacode/shakapacker#214]
- Node 12 is in EOL
- GitHub actions using node 12 have been deprecated (see Annotations [here](https://github.com/shakacode/shakapacker/actions/runs/3554486233))
- New dependencies like Babel Loader 9 and Webpack-cli 5 require Node >= 14(.15)

**Comment by tomdracz** [comment]
Thanks @tagliala @justin808 One for v7, see no reason why we wouldn't do it in the next major release
