### ISSUE TITLE
Update webpack-dev-server configuration

### ISSUE THREAD

**Issue by alexeyr-ci1** [shakacode/shakapacker#217]
1. Not all keys in https://webpack.js.org/configuration/dev-server/ are supported in https://github.com/shakacode/shakapacker/blob/f5dfe4a7c85800c11101309187297ce8030b4422/package/environments/development.js#L17-L41. Should we add support for the rest?
2. The recommended value for `allowed_hosts` is `auto`, not `all` which we have by default. It shouldn't be changed in a patch version, but maybe in 6.6.0 or 7.0.0?
3. `https` key on the Webpack side is deprecated in favor of `server` (which isn't currently supported on our side). Should we add support for it (even if we don't for other keys) and replace `https` in the default config?

**Comment by ahangarha** [comment]
@justin808 Please check this issue. Maybe we can add this to the version 7 milestone.

**Comment by justin808** [comment]
@ahangarha yes fix for 7.0

**Comment by ahangarha** [comment]
@justin808 I am working on this issue and I have some concerns.

I updated `allowed_hosts` and replaced `https: false` with `server: http`. These two changes are breaking ones, so the question is if we should provide backward compatibility? If yes, what is the best strategy?

I was also thinking if we could move this change to the next major release to reduce the number of breaking changes in version 7.

**Comment by ahangarha** [comment]
Done in https://github.com/shakacode/shakapacker/pull/276
