### ISSUE TITLE
NODE_ENV discrepancy between on demand and rake compilation

### ISSUE THREAD

**Issue by bughit** [shakacode/shakapacker#219]
Shakapacker version: master

Expected behavior:

NODE_ENV in rails development env should be development

rake compilation for production can still be done by passing NODE_ENV=production

Actual behavior:

The compile rake task running in rails development env sets NODE_ENV to production (line 23):

https://github.com/shakacode/shakapacker/blob/4416c63b642562e423cd4b5084329166a0bbac45/lib/tasks/webpacker/compile.rake#L22-L32

On demand compilation from rails server, invokes `bin/webpacker` which calls `Webpacker::Runner::run` which sets NODE_ENV, according to RAILS_ENV, to development (line 5)

https://github.com/shakacode/shakapacker/blob/4416c63b642562e423cd4b5084329166a0bbac45/lib/webpacker/runner.rb#L1-L7

**Comment by ahangarha** [comment]
Thanks @bughit for opening this issue and sorry for responding with delay.

The very reason for having `webpacker:compile` is to "compile JavaScript packs using webpack for production with digests".

Is there any particular use case in which you need to use this rake task for compiling for development env?

**Comment by bughit** [comment]
Depending on how rails is started it may not be node aware so on demand compilation will fail.

if this is not a bug or won't fix why is it closed as "completed"?
