### ISSUE TITLE
The install tries to install webpack-dev-server, but it's already installed.

### ISSUE THREAD

**Issue by jcoyne** [shakacode/shakapacker#224]
When I run `rake webpacker:install`, I see this step where `webpack-dev-server` is installed:

```
Adding shakapacker peerDependencies
         run  yarn add @babel/core@7 @babel/plugin-transform-runtime@7 @babel/preset-env@7 @babel/runtime@7 babel-loader@8 compression-webpack-plugin@9 terser-webpack-plugin@5 webpack@5 webpack-assets-manifest@5 webpack-cli@4 webpack-dev-server@4 webpack-merge@5 from "."
```

Then there is another step where it explicitly tries to install it as a devDependency, but this fails as it's already installed:
```
Installing webpack-dev-server for live reloading as a development dependency
         run  yarn add --dev webpack-dev-server from "."
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning "webpack-dev-server" is already in "dependencies". Please remove existing entry first before adding it to "devDependencies".
success Saved 1 new dependency.
info Direct dependencies
└─ webpack-dev-server@4.11.1
info All dependencies
└─ webpack-dev-server@4.11.1
```

**Comment by ahangarha** [comment]
I have also notice there few weeks ago but forgot to open an issue.

I think this should be resolved in generator by removing the one in dev-dependencies and then installing the new one. Am I right?

**Comment by jcoyne** [comment]
Yes this was an old project that was being upgraded, however, shakapacker completely rewrote my package.json, so that I didn't have any devDependencies.

**Comment by Judahmeek** [comment]
The only way to fix this would be to parse the entire package.json for every package that we want to install to see if it is already installed.
