### ISSUE TITLE
Support for Turbo, Rust based webpack successor

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#225]
Let's support https://turbo.build/.

> Turbo is an incremental bundler and build system optimized for JavaScript and TypeScript, written in Rust.

> 
> Why is Turbopack blazing fast?
> Turbopack’s speed comes from its incremental computation engine. Similar to trends we've seen in frontend state libraries, computational work is split into reactive functions that enable Turbopack to apply updates to an existing compilation without going through a full graph recomputation and bundling lifecycle.
> 
> This does not work like traditional caching where you look up a result from a cache before an operation and then decide whether or not to use it. That would be too slow.
> 
> Instead, Turbopack skips work altogether for cached results and only recomputes affected parts of its internal dependency graph of functions. This makes updates independent of the size of the whole compilation, and eliminates the usual overhead of traditional caching.

**Comment by triskweline** [comment]
Another Rust-based bundler [RSpack](https://www.rspack.dev/). Its USP is compatibility with Webpack plugins and config, which might make it a better fit for Shakapacker.

**Comment by justin808** [comment]
> Another Rust-based bundler [RSpack](https://www.rspack.dev/). Its USP is compatibility with Webpack plugins and config, which might make it a better fit for Shakapacker.

PR would be great, @triskweline

**Comment by ahangarha** [comment]
> Please don't.

@lunaisnotaboy Any reason?

**Comment by hueter** [comment]
> Please don't.

Note this is https://github.com/vercel/turbo not https://github.com/hotwired/turbo 😄 not sure if that's what you were worried about?

I'm all for making React + Rails on par with Next.js in terms of bundler/compiler, loving the SWC add-on already 🙌🏻

**Comment by n-rodriguez** [comment]
> Another Rust-based bundler [RSpack](https://www.rspack.dev/). Its USP is compatibility with Webpack plugins and config, which might make it a better fit for Shakapacker.

https://www.rspack.dev/guide/migrate-from-webpack.html

**Comment by tomdracz** [comment]
Closing as no movement. Looking at Turbo it positions itself as a replacement to Webpack so can't quite support it like we do with SWC and esbuild loaders so don't see this being a change on the horizon

**Comment by justin808** [comment]
@tomdracz should we have another task for support for https://www.rspack.dev/?

**Comment by szimek** [comment]
It would be great if Rspack could be supported as well.

We're investigating migrating away from webpack, and rspack seems like a solution that potentially might make it least painful.
