### ISSUE TITLE
Rails webpacker:install

### ISSUE THREAD

**Issue by Dangelo-JAN** [shakacode/shakapacker#241]
I'm following the official documentation

## Setup environment:
- Ruby version: 3.1.2p20
- Rails version: 7.0.4.1
- Shakapacker version: 6.5

**Comment by ahangarha** [comment]
I just cloned your repo and I noticed no issue.

![image](https://user-images.githubusercontent.com/11241315/218309203-a935a881-fc75-4380-a13d-dcdfff113757.png)

But also please follow the documentation carefully. You need to install the "exact" version of Shakapacker. In your Gemfile, you have `gem "shakapacker"` while you should have something like `gem "shakapacker", "= 6.5.6"`.

From the error message, I can say you have an issue with your dev environment.

I close the issue for now but feel free to add more comment if you think this is an issue with Shakapacker.

**Comment by Dangelo-JAN** [comment]
Thanks, I will check my dev enviroment and reinstall all.

thanks for checking... :)
