### ISSUE TITLE
Shakapacker overrides runtimeChunk setting set in local config

### ISSUE THREAD

**Issue by jforkan** [shakacode/shakapacker#247]
## Expected behavior:
Applying `runtimeCheck: false` setting in my webpack.config.js should cause rake assets:precompile to not create separate runtime-xxx.js files

## Actual behavior:
`runtimeCheck: false` setting set in my webpack.config.js was not respected while running rake assets:precompile until I manually applied the same setting at node_modules/shakapacker/package/environment/base.js 

## Setup environment:
- Ruby version: 2.7.7
- Rails version: 7.0.4.2
- Shakapacker version: 6.5.5

**Comment by justin808** [comment]
Zero references: https://github.com/rails/webpacker/search?q=runtimecheck
And this is the only reference here: https://github.com/shakacode/shakapacker/search?q=runtimecheck&type=issues

I don't think this is a bug.

If you want to modify the settings from base.js, you need to manipulate the object.

**Comment by jforkan** [comment]
The default settings I would like to override are within the shakapacker npm package file located within Rails.root at:  node_modules/shakapacker/package/environment/base.js

My expectation was that I would be able to apply settings within Rails.root config/webpack/webpack.config.js, and those would take precedence over those in npm config files, however the "runtimeCheck: false" setting was not applied. 

I _was_ able to successfully set "optimization: { splitChunks: { minSizeReduction: nnn } }" via the same config file. Note that minSizeReduction is not set in the package's base.js file. 

The conclusion I came to was that shakapacker does merge the settings, but prefers the ones in its own base.js. 

For now, editing the file that within the npm package is the workaround I'm using. That seems like a bug, but perhaps there is a way to override the settings that I am missing. 

Thanks!
