### ISSUE TITLE
Incorrect reference to the next release tag

### ISSUE THREAD

**Issue by tomdracz** [shakacode/shakapacker#26]
We're referencing `shakapacker@next` in
https://github.com/shakacode/shakapacker/blob/master/README.md?plain=1#L612
and https://github.com/shakacode/shakapacker/blob/master/lib/install/template.rb#L63-L64

However, there is no `next` tag in the NPM registry, we've got `rc` instead. Compare [shakapacker](https://www.npmjs.com/package/shakapacker?activeTab=versions) vs [rails/webpacker](https://www.npmjs.com/package/@rails/webpacker?activeTab=versions).

Yarn v1 behaves fine and just asks to pick a different release instead. Yarn v3 fails miserably though and refuses to install anything.

Looks like we're using `release-it` and not supplying the tag name so tag guessing game happens at https://github.com/release-it/release-it/blob/master/lib/plugin/npm/npm.js#L202-L210 and just grabs first tag that is not `latest`.

Are we able to retag the RC releases with `next` so everything falls into place @justin808? If not, then we can settle on `rc` and update the code.

**Comment by justin808** [comment]
@tomdracz great catch:

![image](https://user-images.githubusercontent.com/1118459/150667867-c22d0813-afdd-4761-9f90-0fc0dd155686.png)

I added the next tag.

**Is anything else needed before a final 6.0.0 release?**
