### ISSUE TITLE
[Question] Docs show usage of turbolinks, which is deprecated

### ISSUE THREAD

**Issue by DinerIsmail** [shakacode/shakapacker#264]
I noticed in the readme docs that examples show `data-turbolinks-track="reload"`, which from my understanding uses [turbolinks](https://github.com/turbolinks/turbolinks), which hasn't been under active development since 2021.
What does `data-turbolinks-track="reload"` do, and what would be an equivalent without using turbolinks?

![CleanShot 2023-03-22 at 15 25 48](https://user-images.githubusercontent.com/4760294/226954220-77bf1a3f-1e3e-4454-8f20-1b3a72b81934.png)

**Comment by justin808** [comment]
@DinerIsmail I agree. There's probably an equivalent for Turbo.

https://github.com/hotwired/turbo-rails/blob/728b963eb67e1d10a2f16c571f98799076985e2b/app/assets/javascripts/turbo.js#L1622

Change `data-turbolinks-track` to `data-turbo-track`. 

If you like, submit a PR, and I'll merge.
