### ISSUE TITLE
Are the '@babel/preset-typescript' options in the provided babel presets sensible?

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#267]
### Discussed in https://github.com/shakacode/shakapacker/discussions/246

<div type='discussions-op-text'>

<sup>Originally posted by **jennysharps** February  9, 2023</sup>
At the moment, the typescript babel preset looks like this:

https://github.com/shakacode/shakapacker/blob/master/package/babel/preset.js#L33
```javascript
[
  '@babel/preset-typescript',
  { allExtensions: true, isTSX: true }
]
```

According to this issue https://github.com/babel/babel/issues/8924, `isTSX` & `allExtrensions` being set to `true` means the entire codebase is expected to be typescript.  I'm trying to use the provided preset, but as my codebase is a combination of `js` & `ts`, I get errors.

Would it not be more sensible of a default to pass in no options in the preset?  Especially given the fact that one of the benefits of using typescript is the ability to introduce it incrementally to existing codebases.</div>

**Comment by tomdracz** [comment]
Maybe we could do something similar to what we do with SWC? https://github.com/shakacode/shakapacker/blob/master/package/swc/index.js#L28-L33

**Comment by justin808** [comment]
@tomdracz YES, would you like to make a PR? This could be worth getting into the last 6.x release.
