### ISSUE TITLE
shakapacker.lock is not cleaned up

### ISSUE THREAD

**Issue by chrkau** [shakacode/shakapacker#269]
## Expected behavior:

`/tmp/shakapacker.lock` should be cleaned up after compiling assets.

## Actual behavior:

`/tmp/shakapacker.lock` is not cleaned up after compiling assets. This leads to problems when multiple stages under different users are hosted on the same host. If assets are compiled for `staging` e.g. then compiling assets for `production` will fail as it will not be able to create the lock file here:

https://github.com/shakacode/shakapacker/blob/243d3f2e0722f4d3f8d8e653565a270fa183bd00/lib/webpacker/compiler.rb#L59

## Setup environment:
- Ruby version: 3.1.2
- Rails version: 7.0.4.2
- Shakapacker version: 6.6.0

**Comment by justin808** [comment]
1. We should probably have a clear warning if the lock exists. Is the current warning sufficient?
2. @chrkau can you modify your scripts to clean this lock when they start?

**Comment by justin808** [comment]
See #158.

**Comment by chrkau** [comment]
> 1. We should probably have a clear warning if the lock exists. Is the current warning sufficient?

If by "warning" you mean exception then I'd say its pretty clear. :)
But joking aside: It took me a moment to realize why deployment suddenly broke when deploying to a different stage.

> 2\. @chrkau can you modify your scripts to clean this lock when they start?

That's kinda what I'm doing right now: clean the file once the deployment is done.

> See #158.

Yes that would pretty much fix my problem. But I still think it would be good practice to remove the lock file once it's not longer needed - no matter which dir it is created in.

**Comment by ahangarha** [comment]
@chrkau I assume this issue is resolved. If not, please let us know.
