### ISSUE TITLE
`javascript_pack_tag` is outputting paths that start with `//`

### ISSUE THREAD

**Issue by brandoncc** [shakacode/shakapacker#278]
This is what my output looks like in development:

![image](https://user-images.githubusercontent.com/543973/230756702-ae7b35df-3ed2-487f-9eee-c590ed744ee1.png)

And here is what they look like when `RAILS_ENV` is "staging":

![image](https://user-images.githubusercontent.com/543973/230756719-bd38dba6-c448-4ec0-94ec-dc6c867048c6.png)

This makes my browser think that the files live at https://packs/.... because I'm on a url that has an https scheme.

I don't understand why the forward slashes are there or how to fix it. Has anyone seen this before?

**Comment by ahangarha** [comment]
Hi @brandoncc 
Thanks for reporting

Do you have a reproducible project in a public repo? This helps us to debug and resolve the issue.

**Comment by brandoncc** [comment]
Thank you for asking me that @ahangarha. I started thinking about the best way to setup a reproduction app and I stumbled into the cause of the issue. I have had this code in the app for five years with no issue:

```ruby
# Enable serving of images, stylesheets, and JavaScripts from an asset server.
config.action_controller.asset_host = ENV["NO_CDN"] ? "" : "my-subdomain.cloudfront.net"
```

The use case is that I don't want Heroku review apps to use the CDN, so I have `NO_CDN` in the environment on those. I have no idea what I upgraded that changed the way it works, but I need to set the value to `nil` now in order to turn off `asset_host`. It occurs to me now that this was always nicer code and is what I should have used in the beginning:

```ruby
config.action_controller.asset_host =  "my-subdomain.cloudfront.net" unless ENV["NO_CDN"]
```

**Comment by ahangarha** [comment]
Happy to see you could figure out the cause, and the issue is resolved now.

Thanks for your detailed update. It might help someone else facing the same issue.

**Comment by justin808** [comment]
@brandoncc I think an empty string might be truthy in ruby.

How about 
```ruby
# Enable serving of images, stylesheets, and JavaScripts from an asset server.
config.action_controller.asset_host = ENV["NO_CDN"].present? ? "" : "my-subdomain.cloudfront.net"
```

Howevrer, if somebody sets that to "false", you'll get a truth result.

**Comment by brandoncc** [comment]
Thanks for the recommendation, @justin808. You are correct. The only falsey values in Ruby are `nil` and `false`. Unfortunately, your suggestion has the same bug that the original code did. The issue only happened when `NO_CDN` was set on the host (I think it is set to `"true"`, by the way). I was only able to replicate it locally by prepending `RAILS_ENV=staging NO_CDN=true` to my `foreman start` command.

In this situation, there is no difference between `ENV["NO_CDN"]` and `ENV["NO_CDN"].present?` as a condition. The problem I was facing was setting the value of `config.action_controller.asset_host` to `""`. In order to disable the asset host, it seems I now have to set it to `nil`.

Thanks again for taking the time to respond!
