### ISSUE TITLE
Fall back to default config if no custom config exist

### ISSUE THREAD

**Issue by ahangarha** [shakacode/shakapacker#295]
## Expected behavior:
If no custom config file (ex. `./config/shakapacker.yml`) exists in the project, Shakapcker should fall back entirely to the default config file bundled with the gem.

## Actual behavior:
In such a scenario, we break the process and raise an error.

**Comment by ahangarha** [comment]
@justin808 Do we want to implement this?

**Comment by justin808** [comment]
I think it's fine if there's an error message that states you need to run the install.

**Comment by ahangarha** [comment]
Such an error message is shown.
