### ISSUE TITLE
Don't know how to build task shakapacker:install

### ISSUE THREAD

**Issue by mikeshutt** [shakacode/shakapacker#297]
Steps to reproduce
```
rails _7.0.4_ new rails-7-clean --skip-javascript
cd ./rails-7-clean
bundle add shakapacker --strict
bundle install
./bin/rails shakapacker:install

```
Error:
rails aborted!
Don't know how to build task 'shakapacker:install' (See the list of available tasks with `rails --tasks`)

## Expected behavior:
Following the Installation steps, after creating a new rails 7 project and adding shakapacker gem, running shakapacker:install should succeed.

## Actual behavior:
./bin/rails shakapacker:install fails to run with message "Don't know how to build task 'shakapacker:install'"

## Small, reproducible repo:
Have reproduced in multiple environments including WSL and Mac.  Can submit a repo if needed.

## Setup environment:
- Ruby version: 3.2.2
- Rails version: 7.0.4
- Shakapacker version: 6.6

**Comment by mikeshutt** [comment]
Doh!  Thanks, I will try following the correct set of instructions

**Comment by ahangarha** [comment]
I keep this open for a while to prevent creating another similar issue.

**Comment by Guoxweii** [comment]
rails 6..1.7.3 has the same error

**Comment by ahangarha** [comment]
@Guoxweii 
> rails 6..1.7.3 has the same error

Have you noticed https://github.com/shakacode/shakapacker/issues/297#issuecomment-1538558023?

**Comment by jamesnottidge** [comment]
thank you!
This really helped me
But interestingly when I tried to use this command `rails webpacker:install` after installing all the gems in a gemfile (shakapacker was one of the gems) it returned the `Don't know how to build task 'shakapacker:install' (See the list of available tasks with rails --tasks)` error.
However when I added shakapacker with `bundle add shakapacker --strict`, it worked.
Could anyone please explain why this is?
Thank you

**Comment by ahangarha** [comment]
@jamesnottidge Did you get this error message on Shakapacker 7?
