### ISSUE TITLE
webpack-dev-server binds only on ipv6

### ISSUE THREAD

**Issue by ybart** [shakacode/shakapacker#306]
## Expected behavior:

Given the following configuration in webpacker.yml:

```
development:
  dev_server:
    host: localhost
    port: 3035
```

After running the following commands:

```
bin/webpacker-dev-server
```

After running:

```
netstat -an | grep "[.]3035 .*LISTEN"
```

I expected to see webpack-dev-server listening on both IPv4 and IPv6:

```
tcp46       0      0  *.3035               *.*                    LISTEN
```

## Actual behavior:

When booting, I can see:

```
<i> [webpack-dev-server] Loopback: http://localhost:3035/, http://[::1]:3035/
```

After running:

```
netstat -an | grep "[.]3035 .*LISTEN"
```

I can see webpack-dev-server listening only on IPv6:

```
tcp6       0      0  ::1.3035               *.*                    LISTEN
```

A workaround would be to replace host with 127.0.0.1, but in that case it listens only in ipv4 which might cause other issues. Ideally, I would rather have it to bind on both 4 and 6.

In my case, I have an issue because I am proxying traffic with puma-dev, and it does not proxy to the ipv6 address.

It seems the issue occurs when initializing the TCPServer in `dev_server_runner.rb`.

After reading the following blog post :

https://blog.cmol.me/ipv6-ruby-part-3-dual-stack-ipv4-ipv6-tcp-sockets-f0ed9e210de7

I tried to use '::' as host in `webpacker.yml`, which effectively binds to both ipv4 and ipv6:

```
$ netstat -an | grep "[.]3035 .*LISTEN"
tcp46      0      0  *.3035                 *.*                    LISTEN
```

I am not sure if it would be a good idea to use that as the default value. I have not tested it, but I suppose it could cause issues when used on a stack without ipv6 support.

## Small, reproducible repo:

https://github.com/ybart/shakapacker-ipv6-only-binding-issue (last commit contains the workaround listed earlier)

## Setup environment:

- iMac M1 on macOS 13.4
- Ruby version: 3.1.4
- Rails version: 7.0.5
- Shakapacker version: 6.6.0

**Comment by ahangarha** [comment]
Thanks for your report and your update for the workaround. The issue seems to be related to the system configurstion. Though one solution would be to change the default value for host, but I think a better approach is to add this in the documentation.

@justin808 why do you recommend?

**Comment by justin808** [comment]
I think this is a documentation issue. @ybart could you throw in a PR for that?

**Comment by Judahmeek** [comment]
Isn't this actually a webpack-dev-server issue?

**Comment by ahangarha** [comment]
This is already explained in detail on webpack [devServer.host](https://webpack.js.org/configuration/dev-server/#devserverhost) documentation. Since the Shakapacker config file supports the standard webpack configuration for devServer, I don't think we should repeat the same documentation here.

@ybart Thanks again for raising the issue and sharing the solution.
