### ISSUE TITLE
Command "build:css" not found

### ISSUE THREAD

**Issue by wilg** [shakacode/shakapacker#314]
## Expected behavior:

Following the instructions from a Rails app created with `rails new foo -d postgresql -a propshaft -j webpack -c sass`

(trying now to switch to shakapacker)

However, it seems unable to find any relevant yarn commands. There are no such commands defined in package.json

## Actual behavior:

```
› dev
13:46:05 web.1  | started with pid 57791
13:46:05 js.1   | started with pid 57792
13:46:05 css.1  | started with pid 57793
13:46:05 js.1   | yarn run v1.22.17
13:46:05 css.1  | yarn run v1.22.17
13:46:05 css.1  | error Command "build:css" not found.
13:46:05 css.1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
13:46:05 js.1   | error Command "build" not found.
13:46:05 js.1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
13:46:05 web.1  | => Booting Puma
13:46:05 web.1  | => Rails 7.0.5 application starting in development 
13:46:05 web.1  | => Run `bin/rails server --help` for more startup options
13:46:05 web.1  | Puma starting in single mode...
13:46:05 web.1  | * Puma version: 5.6.5 (ruby 3.2.2-p53) ("Birdie's Version")
13:46:05 web.1  | *  Min threads: 5
13:46:05 web.1  | *  Max threads: 5
13:46:05 web.1  | *  Environment: development
13:46:05 web.1  | *          PID: 57794
13:46:05 web.1  | * Listening on http://127.0.0.1:3000
13:46:05 web.1  | * Listening on http://[::1]:3000
13:46:05 web.1  | Use Ctrl-C to stop
13:46:06 css.1  | exited with code 1
13:46:06 system | sending SIGTERM to all processes
13:46:06 js.1   | exited with code 1
13:46:06 web.1  | terminated by SIGTERM
```

## Setup environment:
- Ruby version: 3.2.2
- Rails version: Rails 7.0.5
- Shakapacker version: 7.0.0.rc.1

**Comment by wilg** [comment]
I guess I needed to change `Procfile.dev` to

```
web: unset PORT && bin/rails server
wp-client: bin/shakapacker-dev-server
#wp-server: SERVER_BUNDLE_ONLY=yes bin/shakapacker --watch
```

**Comment by wilg** [comment]
Another issue was I couldn't run `bin/rails shakapacker:install` without also having sprockets installed.

Also, I can't figure out what to do here:

```
Shakapacker can't find application.js in /Users/wil/Code/expedition/maestro/public/packs/manifest.json. Possible causes:
1. You forgot to install node packages (try `yarn install`) or are running an incompatible version of Node
2. Your app has code with a non-standard extension (like a `.jsx` file) but the extension is not in the `extensions` config in `config/shakapacker.yml`
3. You have set compile: false (see `config/shakapacker.yml`) for this environment
   (unless you are using the `bin/shakapacker -w` or the `bin/shakapacker-dev-server`, in which case maybe you aren't running the dev server in the background?)
4. webpack has not yet FINISHED running to reflect updates.
5. You have misconfigured Shakapacker's `config/shakapacker.yml` file.
6. Your webpack configuration is not creating a manifest.

Your manifest contains:
{
  "entrypoints": {
  }
}
```

I'm pretty sure it's issue 6, but I have no idea what to do about it.

**Comment by wilg** [comment]
I had to adjust manifest.js to

```
//= link_tree ../images
//= link_directory ../javascript/packs .js
//= link_directory ../stylesheets .css
```

Not sure if that's the right directory structure or if I've got something turned around

**Comment by wilg** [comment]
I was able to remove sprockets by commenting out:

```
# Rails.application.config.assets.version = "1.0"
```

But now it doesn't seem to include the `rake assets:precompile` task even though you might expect it does from this:

> Shakapacker hooks up a new shakapacker:compile task to assets:precompile, which gets run whenever you run assets:precompile.

But I guess the idea is to enhance precompile if and only if it already exists?

**Comment by ahangarha** [comment]
I don't think this is a bug. As much I understand, this issue is about migration steps from the initial installation to Shakapcker. Am I right? If so, it should be moved to discussions.

CC @justin808

**Comment by wilg** [comment]
Probably. I'll think about today if there's a specific takeaway that would help onboarding, otherwise I'll close it.

**Comment by ahangarha** [comment]
Please share the update
