### ISSUE TITLE
shakapacker:compile is not aliased to assets:precompile when Sprockets is not installed

### ISSUE THREAD

**Issue by jamesst20** [shakacode/shakapacker#323]
Hi,

I currently have a Rails project that is using the very latest Shakapacker gem with the default configuration files on everything.

My Procfile.dev is
```
db: docker-compose up
web: bundle exec rails s -p 3000
worker: bundle exec sidekiq -C ./config/sidekiq.yml
webpack: bin/shakapacker-dev-server
``` 

and locally everything is working as expected. However, when deploying in production on Heroku, the rake `assets:precompile` is never executed.

Relevant part of deployment log
```
...
remote:        Using turbo-rails 1.4.0        
remote:        Using validates_timeliness 7.0.0.beta2        
remote:        Using will_paginate 4.0.0        
remote:        Using will_paginate-bootstrap-style 0.3.0        
remote:        Bundle complete! 55 [Gemfile](https://bitbucket.org/effetmonstre/drsmcn/src/0938cdc9786e31a29742241c7fe7ae04abffa07e/Gemfile) dependencies, 120 gems now installed.        
remote:        Gems in the groups 'development' and 'test' were not installed.        
remote:        Bundled gems are installed into `./vendor/bundle`        
remote:        Bundle completed (0.96s)        
remote:        Cleaning up the bundler cache.        
remote:        Removing bundler (2.3.25)        
remote: -----> Installing node-v16.18.1-linux-x64        
remote: -----> Installing yarn-v1.22.19        
remote: -----> Detecting rake tasks        
remote: -----> Detecting rails configuration        
remote:                
remote:        ###### WARNING:        
remote:                
remote:        There is a more recent Ruby version available for you to use:        
remote:                
remote:        3.1.4        
remote:                
remote:        The latest version will include security and bug fixes. We always recommend        
remote:        running the latest version of your minor release.        
remote:                
remote:        Please upgrade your Ruby version.
....
``` 

Also, executing by hand the precompilation is not working either
```
herokuishuser@5a684956d1f6:~$ bundle exec rake assets:precompile
rake aborted!
Don't know how to build task 'assets:precompile' (See the list of available tasks with `rake --tasks`)
Did you mean?  assets:clean
```

But using the direct command is fine
```
herokuishuser@5a684956d1f6:~$ bundle exec rake shakapacker:compile
I, [2023-06-30T13:13:12.254004 #198]  INFO -- : Compiling...
...
```

## Expected behavior:

The documentation explicitly says https://github.com/shakacode/shakapacker/tree/master#deployment

> Shakapacker hooks up a new shakapacker:compile task to assets:precompile, which gets run whenever you run assets:precompile. If you are not using Sprockets, shakapacker:compile is automatically aliased to assets:precompile. Similar to sprockets both rake tasks will compile packs in production mode but will use RAILS_ENV to load configuration from config/shakapacker.yml (if available).

## Actual behavior:

The command is not aliased

## Setup environment:
- Ruby version: 3.1.3
- Rails version:  7.0.6
- Shakapacker version: 7.0.1

**Comment by ahangarha** [comment]
Please check [deployment documentation](https://github.com/shakacode/shakapacker/blob/master/docs/deployment.md) and share the result

**Comment by jamesst20** [comment]
> Please check [deployment documentation](https://github.com/shakacode/shakapacker/blob/master/docs/deployment.md) and share the result

I am using the same exact buildpacks in the same order. Nginx/brotli/cdn/Capistrano doesn't apply here.

What would you like to know?

**Comment by ahangarha** [comment]
@jamesst20 Thanks for the report. It seems we did updated the documentation for this change. As a result, we do not create `assets:precompile` if it doesn't exist. You need to run `shakapacker:compile` in your build process.

We will update the documentation soon.

**Comment by justin808** [comment]
@ahangarha you are not correct. We need to add this back ASAP.

https://github.com/shakacode/shakapacker/blame/1fcf9d324aaed90002cbf398563a5a394cb98041/lib/tasks/webpacker/compile.rake#L27-L36C6

We were supposed to remove yarn:install not the whole condition.

@jamesst20 we'll have a release out ASAP.

**Comment by ahangarha** [comment]
@jamesst20 Thanks for reporting. I appreciate if you test [fix-missing-assets-precompile-task](https://github.com/shakacode/shakapacker/tree/fix-missing-assets-precompile-task) branch and confirm the fix.
