### ISSUE TITLE
Can we use shakapacker with npm instead of yarn?

### ISSUE THREAD

**Issue by DinerIsmail** [shakacode/shakapacker#334]
Our team wants to migrate away from yarn v1 as it's currently unmaintained, and yarn v2/v3 are too much of a change. Is it possible to use shakapacker with npm?

After I replaced yarn with npm and deleted yarn, I get a `No such file or directory - yarn` error when I try to bundle the code.

**Comment by ahangarha** [comment]
Currently no.

There is a similar issue here: #195

@justin808 Since you opened the other issue, is there any update regarding adding such a feature?

**Comment by justin808** [comment]
I'm open to a PR that does this.

**Comment by ahangarha** [comment]
@DinerIsmail Would you like to work on this in any near future?

**Comment by DinerIsmail** [comment]
Hi @ahangarha, unfortunately I won't have capacity to that. Thank you for clarifying though - what we did in the end is upgraded to Yarn Berry (v3) which gives us several of the features we wanted from NPM.
I will close this issue for now.
