### ISSUE TITLE
Improvements to CI

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#34]
I think the gem should have 2 big improvements to CI:

1. A sample app, like `/spec/dummy` https://github.com/shakacode/react_on_rails/tree/master/spec/dummy
2. CI steps that run `rails new` and the webpacker generator, and then a test, like [those here in React on Rails](https://github.com/shakacode/react_on_rails/tree/master/rakelib)

Take a look at https://github.com/shakacode/react_on_rails/blob/master/Rakefile and https://github.com/shakacode/react_on_rails/blob/master/.github/workflows/main.yml.

**Comment by saiqulhaq** [comment]
for the first point
I found that there are `mounted_app` and `test_app` in the `test` directory
So we need another app to test the Shakapacker generator command?

**Comment by justin808** [comment]
It would be good for CI to run rails new and confirm that a simple app "works" with an integration test.

**Comment by saiqulhaq** [comment]
ok I will send a PR for it

**Comment by justin808** [comment]
@saiqulhaq would be awesome if such a change supported showing the bug fixed by #47! (CC @tomdracz)

**Comment by Judahmeek** [comment]
Closed as stale.
