### ISSUE TITLE
7.0.3 doesn't seem to actually be released

### ISSUE THREAD

**Issue by swrobel** [shakacode/shakapacker#347]
It's [called out in the Changelog](https://github.com/shakacode/shakapacker/blob/master/CHANGELOG.md#v703---july-7-2023) as having been released July 7, but it isn't on Rubygems...

**Comment by Judahmeek** [comment]
@justin808 @ahangarha

**Comment by ahangarha** [comment]
Thanks @swrobel 
V7.0.3 just released.
