### ISSUE TITLE
yarn 2 + pnp modules?

### ISSUE THREAD

**Issue by woodhull** [shakacode/shakapacker#35]
Ruby version: 3.0
Rails version: 6.1
Webpacker version: 6.0.2

Desired behavior: yarn 2 + pnp modules. 

Actual behavior: I'm not clear on whether this is supposed to work out of the box or not. There was a webpacker issue that was closed before migrating to this repository.

**Comment by tomdracz** [comment]
AFAIK, Yarn 2(3) should be supported but no PnP modules support yet. Haven't used PnP anywhere yet so hard to say what's actually needed in supporting this.

https://yarnpkg.com/getting-started/migration#step-by-step setting `nodeLinker: node-modules` is a must at the moment so we opt out of PnP modules. This is actually documented in the CHANELOG.md but bit buried away.

**Comment by justin808** [comment]
Should this issue stay open?
