### ISSUE TITLE
`import`ed css in main pack entrypoint not actually showing up on page.

### ISSUE THREAD

**Issue by SeedyROM** [shakacode/shakapacker#351]
I'm in the middle of upgrading `webpacker` from a very old version to `shakapacker`. It's been a bit of process but I have everything working including SSR for my React components.  I've basically ripped all the webpack configurations from a newly generated rails app with shakapacker 7.0, however I'm not using CSS modules.

The problem is the styling, right now my `import '<path>/application.css';` doesn't seem to have any effect on the output. Even when adding the include style tag (this worked in webpacker 4.0):

**`application.js`**
```js
...
import "../stylesheets/application.css";
...
```

**Layout:**
```erb
...
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
...
```

Am I missing something?

## Expected behavior:
CSS should be loaded by css-loader!

## Actual behavior:
No CSS is emitted or loaded.

**Comment by ahangarha** [comment]
May you please make a demo repo?

**Comment by justin808** [comment]
It's definitely not a bug until we have reproduction steps.

**Comment by SeedyROM** [comment]
Must have missed the slack channel in the readme! I'll ask there.
