### ISSUE TITLE
Ensure consistent version of package and gem

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#36]
Let's have a check that ensures the shakapacker npm version matches the gem version if the npm package is used for webpack configuration.

I think we just check if the npm package is installed (in package.json) and assume that if it's not there, then someone has a completely custom webpack config setup.

Example code:
https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/version_checker.rb

@tomdracz thoughts?

**Comment by tomdracz** [comment]
@justin808 Makes sense to me, good shout!

Probably should update the installation scripts and docs while we're at it, to use bundle`--strict` and yarn `--exact` options.

Thanks for react-on-rails examples, I'll take a stab at it over the coming days.
