### ISSUE TITLE
Support Yarn 4+

### ISSUE THREAD

**Issue by ColeWalker-Drizly** [shakacode/shakapacker#377]
_Notice: A feature request describes a suggested improvement. If you have a debugging or troubleshooting question, please open a discussion on the [Discussions Tab](https://github.com/shakacode/shakapacker/discussions). Otherwise, remove this line and fill out the following sections._

## Desired behavior:

Allow us to use Shakapacker with Yarn 4+. 

## Actual behavior:

Currently the process will exit with an error if using a Yarn version >3.

## Setup environment:
- Ruby version: 
- Rails version: 
- Shakapacker version:

**Comment by Judahmeek** [comment]
What sort of error?

Is this related to https://github.com/shakacode/shakapacker/issues/371?

**Comment by justin808** [comment]
@G-Rath I bet we just need to finish your release.

@ColeWalker-Drizly can you please try out:

https://www.npmjs.com/package/shakapacker/v/7.2.0-rc.0
https://rubygems.org/gems/shakapacker/versions/7.2.0.rc.0

**Comment by G-Rath** [comment]
oh has https://github.com/shakacode/shakapacker/pull/369 not actually been released? I'm happy if you want to release v7.2.0 @justin808 - we've had a few people say its working and `package_json` is still feature flagged for now so I don't see any reason to keep it as an rc.

**Comment by G-Rath** [comment]
Yup thats is exactly what #369 fixes

**Comment by ahangarha** [comment]
@ColeWalker-Drizly Please share the update with us.
