### ISSUE TITLE
Pin glob version to 9.X

### ISSUE THREAD

**Issue by Ch1g** [shakacode/shakapacker#384]
Hi!

https://github.com/isaacs/inflight/issues/5

Considering the issue has been open 6 years and the inflight.js file has not been edited in 7 years, I think it's likely this isn't going to be addressed here. If your situation is like mine, you are here because Snyk started complaining about this yesterday (why only yesterday? Who knows...) and a package you depend on depends on this package or, more likely, a package you depend on depends on glob which at one point in time depended on inflight. The actively-maintained glob package no longer depends on inflight, so your best bet is to (a) pin your glob version to something greater than v9, (b) to (respectfully) bug package maintainers to upgrade their glob dependency version string, or (c) to ignore the issue because it's probably not doing you real harm anyway. For myself, it's option (c).

shakapacker@7.0.0 requires glob@^7.2.0 which requires inflight "^1.0.4"

Are there any plans to upgrade glob version?
OR
maybe any help/resources required to ping Shakapacker to a newer version of glob package?

**Comment by Judahmeek** [comment]
Since `inflight` is an npm package, you could always add a resolution to your package.json.

I'll see if we can't address this more permenantly though.
