### ISSUE TITLE
`hmr: false` does not disable Hot Module Replacement

### ISSUE THREAD

**Issue by thedanbob** [shakacode/shakapacker#390]
Starting with version 4, webpack-dev-server defaults to Hot Module Replacement enabled:
https://github.com/webpack/webpack-dev-server/blob/540c43852ea33f9cb18820e1cef05d5ddb86cc3e/CHANGELOG.md?plain=1#L561
https://github.com/webpack/webpack-dev-server/blob/540c43852ea33f9cb18820e1cef05d5ddb86cc3e/lib/Server.js#L1081

Shakapacker assumes the default is disabled: If `hmr: true` the `--hot` flag [gets added](https://github.com/shakacode/shakapacker/blob/0b0e1c71a8c3e087d47efb5c5aea960842a179da/lib/shakapacker/dev_server_runner.rb#L89) to the webpack-dev-server command, but `hmr: false` does nothing. To actually disable HMR you must add `hot: false` to shakapacker.yml or the `--no-hot` command line flag.

**Comment by justin808** [comment]
@thedanbob good find. Any chance that you can submit a PR to resolve this?

**Comment by thedanbob** [comment]
Sure thing, I'll work on that later today.
