### ISSUE TITLE
Not clear how to avoid the `relative_url_root` deprecation message 

### ISSUE THREAD

**Issue by tagliala** [shakacode/shakapacker#399]
Shakapacker 7.2.0 deprecated `relative_url_root`, but is not clear from changelog, the documentation, or a freshly generated config how to avoid this warning.

I'm not sure what `relative_url_root` is used for, but probably shakapacker should print the deprecation error only if it is being used (have a value different from `blank`?)

## Expected behavior:

Have an option/documentation/config entry to avoid the deprecated behavior

## Actual behavior:

Running specs logs a warning on the console.

```
The usage of relative_url_root is deprecated in Shakapacker and will be removed in v8.
```

## Small, reproducible repo:

diowa/ruby3-rails7-bootstrap-heroku#702

https://github.com/diowa/ruby3-rails7-bootstrap-heroku/actions/runs/7364428208/job/20044793977#step:8:14

<img width="720" alt="image" src="https://github.com/shakacode/shakapacker/assets/556268/55df2978-7bd9-48c6-ad69-2408afc9268e">

## Setup environment:
- Ruby version: 3.3.0
- Rails version: 7.1.2
- Shakapacker version: 7.2.0

**Comment by ahangarha** [comment]
This is not a bug.

We will remove `relative_url_root` in the next major release. We cannot remove it from the compilation process now. So, we must inform developers to ensure their project is not dependent on it.

Does this deprecation message cause any issues in your project?

**Comment by ahangarha** [comment]
@tagliala #400 should solve the issue. The deprecation message will be shown only if `relative_url_root` is set.

Does it work for you?

**Comment by tagliala** [comment]
Thanks for the prompt answer!

> This is not a bug.

I do agree. I was not sure this was a feature request either, and I was even thinking to open a discussion, but in the end I decided to use the bug template the same, apologies for the confusion

> Does it work for you?

I can confirm this works, diowa/ruby3-rails7-bootstrap-heroku@e03ee10d9cbc84b93c94812ebb394e117076c6ed

Action: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/actions/runs/7365381926/job/20046638615#step:8:1

Thanks again and Happy New Year!

**Comment by ahangarha** [comment]
Thanks for reporting the issue
