### ISSUE TITLE
Webpacker can't find subdir/image.png in manifest.json

### ISSUE THREAD

**Issue by honzasterba** [shakacode/shakapacker#44]
Ruby version: 3.03
Rails version: 7.0.1
Webpacker version: 6.0.2 (same for js and gem)

Expected behavior:
- put an image file into /app/javascript/images/subdir/image.png
- use `image_pack_tag "subdir/image.png"` in view
- image should be found by webpacker and rendered

Actual behavior:
Error is raised: Webpacker can't find subdir/image.png in .../manifest.json

Small, reproducible repo:
https://github.com/honzasterba/packer-test

**Comment by honzasterba** [comment]
first I thought I was doing something wrong, but this just seems like a big source of incompatibility between webpacker and shakapacker

webpack-asset-manifest says: will generate a JSON file that matches the original filename with the hashed version

so maybe thats it? instead of file-path->hashed-version it generates only file-name->hashed version?

there is a difference to how to manifest used to look like with webpack5:
`media/subdir/image.png": "/packs/media/images/subdir/image-HASH.png`

now with shakapacker:
"static/image.png": "/packs-test/static/image-bd51daf42131d4298622.png"

**Comment by tomdracz** [comment]
Looks like this was open issue with rails/webpacker. For more see https://github.com/rails/webpacker/issues/2956. Likely changed in https://github.com/rails/webpacker/pull/2802 Need to dig into this and figure out what was the reason for this change.
It did trip me up when I was upgrading, referencing asset name without a folder seems to work but might cause some issues as outlined in the discussion at rails/webpacker above

**Comment by tomdracz** [comment]
@honzasterba Can you try out the changes in https://github.com/shakacode/shakapacker/pull/47 and see if that fixes the issue for you?

**Comment by honzasterba** [comment]
will do!

**Comment by honzasterba** [comment]
I have checked and I can verify that #47 fixes the issue

**Comment by tomdracz** [comment]
Thanks! Need to give it few me spins but hopefully we can merge and release soon!

**Comment by justin808** [comment]
Awesome work guys!

**Comment by justin808** [comment]
I'll release 6.1.0 on Friday.
