### ISSUE TITLE
Add support for https://github.com/privatenumber/esbuild-loader like SWC

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#49]
Check out what we did for SWC:

https://github.com/shakacode/shakapacker/pull/29

And create a PR here, like what we did for SWC:
https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh

**Comment by tomdracz** [comment]
Just some notes for anyone looking to pick this up!

Actual new rule setup should be super straightforward - SWC PR linked can be used as good basis on how to determine if loader is available, how to have rule as a function so current filename can be processed etc Easy peasy!

While at it, it could be good to see if we can also swap out Terser for esbuild, which should be faster. More info in article at https://blog.logrocket.com/webpack-or-esbuild-why-not-both/

HOWEVER, unlike Babel & SWC that mostly have feature parity, there's few gotchas with esbuild like:
- No support for HMR (reference https://github.com/evanw/esbuild/issues/645)
- No support for ES5 (reference https://github.com/evanw/esbuild/issues/297)
- No automatic polyfills (reference https://twitter.com/appfactory/status/1434130479293288450?s=21)

This is non-exhaustive list but it does show that using esbuild might not be suitable for everyone. Projects that don't use JSX, don't need to support older browsers might get a better experience here.

Performance boost could be worth it though so it will be nice to offer this as an option!

**Comment by tomdracz** [comment]
Looks like I've linked to the wrong issue in the PR, d'oh! We can close this one.

**Comment by justin808** [comment]
Fixed in #53
