### ISSUE TITLE
Tests failed due to `uninitialized constant Rack::Handler`

### ISSUE THREAD

**Issue by adriangohjw** [shakacode/shakapacker#498]
## Expected behavior:

Tests should pass

## Actual behavior:

Tests failed due to `uninitialized constant Rack::Handler`

## Small, reproducible repo:

Not a repo, but it's happening in the latest commit
Reference: https://github.com/shakacode/shakapacker/actions/runs/9575629216/job/26400796835

## Setup environment:
- Ruby version: 2.7
- Rails version: 7.1.x
- Shakapacker version: 8.0.0

**Comment by justin808** [comment]
@adriangohjw can you investigate a fix?

**Comment by adriangohjw** [comment]
@justin808 here's my findings so far:

- Error is caused by `unless Rack::Handler::Puma.respond_to?(:config)` in the `capybara` gem in [versions 3.39.2 (or earlier)](https://github.com/teamcapybara/capybara/blob/d4ee8639a38e8a204e19d6039d7bae63c5042113/lib/capybara/registrations/servers.rb#L31)
- Seems like a similar issue to https://discuss.rubyonrails.org/t/rails-7-1-2-upgrade-rack-handler-deprecation-warning/84166/3
- While the issue has been [fixed in version 3.40.0](https://github.com/teamcapybara/capybara/blob/master/History.md#version-3400) onwards, support for ruby 2.7 has also been dropped in that version, thus latest compatible version is 3.39.2
