### ISSUE TITLE
Rake task `webpacker:compile` fails when `which` is not installed

### ISSUE THREAD

**Issue by cbochs** [shakacode/shakapacker#530]
It appears that the yarn check depends on `which` being available on the system for the check to succeed. If it is not, then `webpacker:compile` fails with a relatively ambiguous error of:

```
$ bundle exec rake webpacker:compile

Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/
Exiting!
```

This occurs when running ruby/rails on a docker container which does not have `which` installed by default (e.g. an `almalinux` image).

## Small, reproducible repo:

```
$ docker run --rm -it almalinux

# dnf install -y epel-release
# dnf install --enablerepo-crb -y ruby-devel gcc libyaml-devel yarnpkg
# gem install shakapacker -v '6.5.2'

# type which
bash: type: which: not found

# type yarn
yarn is /usr/bin/yarn

# echo 'import "/usr/local/share/gems/gems/shakapacker-6.5.2/lib/tasks/webpacker/check_yarn.rake"' > Rakefile

# rake webpacker:check_yarn
Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/
Exiting!
```

## Setup environment:
- Ruby version: 3.0.7
- Rails version: 6.1.0
- Shakapacker version: shakapacker-6.5.2

**Comment by tomdracz** [comment]
Is there any good reason that you need to stick with quite an old version of Shakapacker @cbochs ? We're two major versions ahead now at version 8.0.2 and we've removed the check yarn task a while back https://github.com/shakacode/shakapacker/pull/443

The code in question was originally inherited from webpacker gem

**Comment by tomdracz** [comment]
Closing as not relevant to the newer version of Shakapacker as far as I can see and limited value in trying to get older versions to play well with more exotic systems
