### ISSUE TITLE
Option to not use style-loader

### ISSUE THREAD

**Issue by cheald** [shakacode/shakapacker#68]
Ruby version: 2.7.4
Rails version: ~> 5.2.6
Webpacker version: 6.1.1

Desired behavior:

mini-css-extract-plugin is [capable of HMR now](https://github.com/webpack-contrib/mini-css-extract-plugin/pull/334). I'd like the ability to opt into just using it all the time, even when HMR is set in webpacker.yml. I'd like to get style-loader out of the dev pipeline so that my development and production environments more closely match, while retaining HMR. It turns out this isn't too hard!

Actual behavior:

Currently, `hmr: true` in webpacker.yml sets `Webpack.inlining_css?`, which prevents stylesheet_pack_tag form emitting `<link>` tags for CSS, on the assumption that style-loader is in play. I monkey patched my install with:

```ruby
class Webpacker::Instance
  def inlining_css?
    false
  end
end
```

And my Webpack css loader with:

```javascript
// Swap all style-loader rules for mini-css-extract-plugin, even if HMR. MCEP supports HMR now.
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
webpackConfig.module.rules.forEach((rule) => {
  if ("test.css".match(rule.test) || "test.scss".match(rule.test)) {
    rule.use = rule.use.map((loader) => {
      if (loader === "style-loader") {
        return MiniCssExtractPlugin.loader;
      } else {
        return loader;
      }
    });
  }
});
```

and it works just dandy.

The fix should be as simple as allowing the explicit disabling of inlining css (perhaps `inlineCss: false` in webpacker.yml), then updating the Webpack::Instance#inlining_css? method and its partner in `shakapacker/package/inliningCss.js` to respect the flag if it's set.

**Comment by justin808** [comment]
@cheald can you submit a PR? This sounds reasonable.

Yes, we can have `inline_css` inside of the HMR config.

@tomdracz, thoughts?

**Comment by cheald** [comment]
Sure, I whipped something up. If you have further direction on what you'd like to see, I'm happy to further improve it.

**Comment by matoni109** [comment]
@cheald just i've got a `rails 5` setup just wondering where you placed below code ? 

I've tried `lib/webpacker/instance_methods.rb`

```ruby
class Webpacker::Instance
  def inlining_css?
    false
  end
end
```

**Comment by justin808** [comment]
@matoni109 please see comments here: https://github.com/shakacode/shakapacker/pull/75/files

**Comment by tomdracz** [comment]
@justin808 good to close!
