### ISSUE TITLE
SWC Config Output is Strange, Wrong-Seeming

### ISSUE THREAD

**Issue by dleavitt** [shakacode/shakapacker#77]
Was playing around with the swc option (neat!) and encountered this. Happy to take a pass at fixing.

Ruby version: 3.1.1
Rails version: 7.0.2.2
Webpacker version: 6.1.1

### Expected behavior:

The following, rather unambitious Javascript, when compiled with `webpack_loader: "swc"` and no further customization to the ~~web~~ **shaka**packer config, should compile to Javascript that works.

**Input Javascript**

```javascript
class B {}

class Thing extends B {
  constructor(n) {
    super()
    this.name = n
  }
}

const t = new Thing("name")
```

### Actual behavior:

It compiles to to something very strange that doesn't polyfill classes correctly.

**Output Javascript**
```javascript

// ... elided polyfill stuff

var B = function B() {
    "use strict";
};
var Thing = /*#__PURE__*/ function(B) {
    "use strict";
    _inherits(Thing, B);
    function Thing(n) {
        var _this;
        _this = B.call(this); // "_this" is always going to be undefined here
        _this.name = n; // so this line will always be an error
        return _this;
    }
    return Thing;
}(B);

var t = new Thing("name");

```

The swc config output looks like the below. The stuff under `env` looks like maybe it was copied directly from the Babel config. This is exacerbated by the fact that shakapacker merges its default swc config with the custom one you supply.

**Generated SWC Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    }
  },
  "sourceMaps": true,
  "env": {
    "coreJs": "3.8",
    "loose": true,
    "exclude": [
      "transform-typeof-symbol"
    ],
    "mode": "entry"
  }
}
```

### Small, reproducible repo:

No repo yet, but to reproduce:

- Go here https://swc.rs/playground. 
- Paste the "Input Javascript" above into the "Input" field.
- Click on the "Edit as JSON" button.
 - Add a `console.log` somewhere in your shakapacker config to output your webpack config. Grab the SWC part (or just grab the it from the above) and paste the results in.

**Comment by justin808** [comment]
@dleavitt would love to get a PR! 😄 😄 😄

**Comment by tomdracz** [comment]
@dleavitt Looks like its `loose` option under env that causes this behaviour, not sure why though https://swc.rs/docs/configuration/supported-browsers#additional-options

Doesn't help that SWC also defines loose at other level https://swc.rs/docs/configuration/compilation#jscloose

Had some issues with SWC docs so not sure what's going on here. I've opened up issue here https://github.com/swc-project/swc/issues/3943

For now @dleavitt if you want to open up a PR I would do the following:
- remove `env.loose` option from the default config
- change `coreJs` setting to integer 3 rather than string `3.8` (seems like this is what SWC is expecting)

**Comment by tomdracz** [comment]
BTW looks like reported issue in SWC repo has been closed with PR so hopefully all will be good in next SWC release.

Still, happy for us to get rid of the loose option. I've only added it for parity with default babel config but we might as well leave that config to the user.

**Comment by dleavitt** [comment]
I was also confused by the "loose" in two different places thing.

PR @ #79  

happy to update it to remove `loose` entirely - seems like a good idea to remove unless it has the potential to make migration from babel harder.

**Comment by tomdracz** [comment]
Docs talk about `jsc.loose` as equivalent of Babel setting so let's go with changes as per your PR @dleavitt Thanks!
