### ISSUE TITLE
Suggestions for the name of this project

### ISSUE THREAD

**Issue by justin808** [shakacode/shakapacker#9]
_Warning, the final name of this fork and evolution of rails/webpacker is still pending waiting on community feedback._ 

What name would make sense so the name is not confusing with old rails/webpacker?

Since the old repository will not be transferred, we need a new name.

**Comment by t27duck** [comment]
`webpack-pipeline`?  `webpacking`? `webpack-rails`?

**Comment by justin808** [comment]
We went with `shakapacker`.
